### ISSUE TITLE
taxa lookup for species says "No taxa found."

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#100]
In the taxa lookup, e.g. [Species: Escherichia coli](https://bugsigdb.org/Special:RunQuery/Taxon?Taxon%5BNCBI%5D=562&Taxon%5BBody%20site%5D=&Taxon%5BCondition%5D=&_run=1) it says "No taxa found." because there are no descendants found. "No taxa found" may be misleading for someone who doesn't have that context, and something like "No descendants found" (or is it "No direct descendants found"?) would be a more intuitive message.

**Comment by tosfos** [comment]
We elected to go with "No further descendants found." Please review [here](https://bugsigdb.org/Special:RunQuery/Taxon?Taxon%5BNCBI%5D=562&Taxon%5BBody%20site%5D=&Taxon%5BCondition%5D=&_run=1).

**Comment by lwaldron** [comment]
Looks good.
