### ISSUE TITLE
Fine-graining of Pages with missing NCBI ID

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#101]
I spent some time trying to clean up https://bugsigdb.org/Category:Pages_with_missing_NCBI_ID, and kept notes on its talk page (https://bugsigdb.org/Category_talk:Pages_with_missing_NCBI_ID). What I found is there are a few categories of unmapped taxa in these signatures:
1. not reviewed
2. reviewed but not resolved, should revisit
3. reviewed and cannot be fixed

Currently the only way I can keep track of these is on the talk page (where I took notes, and said "all signatures up to ... have been reviewed), but this will become unmanageable as more unmapped taxa appear, and reviewers are likely to waste their time trying to map taxa that have already been determined difficult or impossible to resolve. Can you think of a way to annotate unmapped taxa according to these three categories, in a way that pages on https://bugsigdb.org/Category:Pages_with_missing_NCBI_ID could be distinguished according to them?

**Comment by tosfos** [comment]
Will do.

**Comment by tosfos** [comment]
I can see these options for how to create the Taxa review system:

1. A single review system for all taxa contained in a single signature.
2. A review system for each individual taxon contained in each signature.

I think option 1 is easier, but clunky. A signature could contain multiple taxa that each need work. For example, one taxon could be unresolveable, while the other should be revisited. So how would the status be set? The whole taxa section could be assigned the "lowest status" and then a textarea could allow free-form explanation of the status like "Taxon A is not resolveable for reason X. Taxon B should be revisited."

Option 2 shouldn't be too difficult. Is there any need for there to be a review system for taxa that have been assigned an NCBI ID? I could imagine a situation where an NCBI ID was assigned to it, but is only partially accurate, or we're not sure if there's accurate. Either way, I would imagine a small review icon next to each taxon (or each unmapped taxon) that is either a check mark, warning mark or error (or similar) and then hovering over it would display information about the review and allow modifying this information. We'd definitely want to improve the taxon list layout, which is a good idea anyway.

Please let me know what you think.

**Comment by lwaldron** [comment]
Option 2 sounds great if it isn't too difficult. I certainly have resolved some names to NCBI ID's where I thought, "this isn't perfect but it's better than nothing" because at least it identifies the correct genus or higher rank. I don't think we would go through a review process for every single taxon, but for ones that are flagged for review because they are unmapped or the curator is uncertain about the taxid, this will be a very nice feature.

**Comment by tosfos** [comment]
This sounds good! Should there also be a field where a reviewer can add comments explaining why a status was assigned?

**Comment by lwaldron** [comment]
Yes that'd be useful!

**Comment by tosfos** [comment]
Please see what we have in mind for the taxon review [here](https://bugsigdb.org/Special:FormEdit/TSig_Review/Review:Study_513/Experiment_2/Signature_1/1301?namespace=Review).

I think it makes sense to split into 2 different fields, but I"m not sure exactly how they should work. Conceptually, a taxon can be Reviewed or Unreviewed, and if it is Reviewed it can be assigned a Score, which can either be "Resolved", "Unresolved (but revisit)" or "Can't fix". The "review" status and the "score" that the review results in are really 2 different things though.

Please let me know what you think.

**Comment by lwaldron** [comment]
It looks good! Questions/comments:
1. Reviewed vs Incorrect don't exactly seem like complements, and "Incorrect" + "Can't fix" would have unclear meaning to me. I wonder if this should be "Flag for review" vs "No known issues"? Unless you mean for a state of "Incorrect" to be automatically applied for unmapped taxa? Otherwise, if whether a taxon has been reviewed can be implied from whether a review has been saved, then a flagging item here sounds more useful. If these are attributes to be also associated with unreviewed taxa, and if you use a "flag" state instead, it would have a default of "No known issues". Using current language, after reviewing a taxon and deciding on a score of "can't fix", it seems it would be both "Reviewed" and "Incorrect". Obviously I'm a little confused here, primarily about whether these attributes will belong to all taxa in all signatures, or only to those that have been reviewed.
2. The "score" looks useful and intuitive as-is, as does the review box.
3. It may be better to calculate the reviewer and review date without making them reviewer-editable? I can't think of a use case for letting someone change either of these fields, but correct me if there is one.  This is a minor point. 
4. I would expect a state of "No known issues" in combination with a score of "not resolved" or "cannot fix" to impossible, but that is also a minor point.

**Comment by lwaldron** [comment]
By the way, I just noticed and loved the little taxon review icons with their mouseovers! From https://bugsigdb.org/Study_513/Experiment_2/Signature_1:
![image](https://user-images.githubusercontent.com/639942/135544789-4306954a-6e56-4485-bad7-3e808e9344f6.png)

One suggestion: for people less familiar with our terminology, "Issues with this entry" might be more intuitive for the mouseover? Review might be interpreted as "read more about it".

**Comment by tosfos** [comment]
> I think was the default that most individual taxa don't ever need to be reviewed

I was intending for the "Needs Review" status to be the same as your "OK (default)". I know it sounds like these are very different. But how would you know that a taxon doesn't need to be reviewed unless someone reviewed it and said "Resolved" (or "OK")? My idea was that all taxa would default to "Needs Review" until someone reviewed them and marked them "Resolved".

I guess if the vast majority of taxa don't need to be reviewed, we can default to "OK". But that would mean that ALL taxa would be set to "OK" until someone changed it.

**Comment by tosfos** [comment]
We have a first draft of this feature ready for review. You can see the new display of taxon review states [here](https://bugsigdb.org/Study_513):
![image](https://user-images.githubusercontent.com/10228795/141198706-533c68d6-f7f9-44ff-9984-80f4543408c0.png)

And [here](https://bugsigdb.org/w/index.php?title=Review:Study_513/Experiment_2/Signature_1/32207&action=formedit) is a sample review:
![image](https://user-images.githubusercontent.com/10228795/141198947-ade7ec96-63b3-4d10-8518-948a62a8fe37.png)

We're still actively working on improvements, but any feedback would be most welcome. Thanks!

**Comment by lwaldron** [comment]
Looks great and I've been trying it out already. A few small questions:
1. What do the black cross-through speech bubbles on https://bugsigdb.org/Study_559 mean?
![image](https://user-images.githubusercontent.com/639942/141526914-44913e2f-4eed-491b-aa26-82b465ab1df9.png)
2. What does "resolved into (please enter 1 or more characters)" in the review mean? E.g.:
![image](https://user-images.githubusercontent.com/639942/141527025-8b06ef79-2720-41ff-a9b3-d27a6eff63c3.png)
3. Where can we find a list of all pages listed as "Not fixable", "Needs Review", or "Follow-up needed"?

**Comment by tosfos** [comment]
> What do the black cross-through speech bubbles on https://bugsigdb.org/Study_559 mean?

I'll get back to you on this.

> What does "resolved into (please enter 1 or more characters)" in the review mean?

I'm not sure if it's actually needed. The idea is that if a Review becomes not valid, because the taxon has been changed, this would track where the taxon went. It takes a Taxon ID. In other words, if a Study contained a taxon ID like "2", and then this was changed into something more specific like "33039", you would enter "33039" under "Resolved into". What will happen is that the old Review page for the "2" taxon becomes, basically, inaccessible. But if someone did find it and wanted to know what happened to this taxon, they would be able to figure out why there is no longer a "2" taxon in the Signature.

I think this is probably confusing and not necessary, and we should probably just remove that field. Please let me know if you disagree.

> Where can we find a list of all pages listed as "Not fixable", "Needs Review", or "Follow-up needed"?

That is not yet completed, but you can see it in-progress, [here](https://bugsigdb.org/Special:RunQuery/Review_score?Review_score%5BReview%20score%5D=Not%20fixable&_run=1).

**Comment by tosfos** [comment]
I believe this can be closed.
