### ISSUE TITLE
Study lookup returns page with `::` codes and no experiments or signatures

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#102]
I expected the [Study lookup](https://bugsigdb.org/Project:Study_lookup) to return a regular study page like https://bugsigdb.org/Study_21, but instead it returns a study only, with a lot of `::` in it and no Experiments or Signatures (screenshot of [Study 21 as returned by study lookup](https://bugsigdb.org/Project:Study_lookup?title=Project%3AStudy_lookup&pfRunQueryFormName=Study+filter&Study+filter%5BStudy%5D=16S+gut+community+of+the+Cameron+County+Hispanic+Cohort&Study+filter%5Bmap_field%5D%5BStudy%5D=true&wpRunQuery=Study+lookup&pf_free_text=) below). Can the study lookup be made instead to link to the regular study, e.g. in this example https://bugsigdb.org/Study_21? 

![image](https://user-images.githubusercontent.com/639942/132917394-e33a6c94-530b-4423-9c5d-ef0f17eeb70b.png)

**Comment by tosfos** [comment]
Will do.

**Comment by tosfos** [comment]
We created a new Study lookup method. Please review [here](https://bugsigdb.org/Project:Study_lookup). It has a really nice search feature built-in too.

**Comment by lwaldron** [comment]
That is great! It's almost too fast and simple, people will think what it's
doing is trivial :D But seriously, it's really nice. The only quirk I
noticed was the ordering of studies 1, 10, 100, 101, 102, ... - the most
intuitive sorting might be alphabetically by title but that really doesn't
matter.

**Comment by tosfos** [comment]
We changed the sorting to alphabetically by title, which does make much  more sense. And if you liked the old one, I think you'll love it now! We added some really amazing study sorting. [Please let me know what you think](https://bugsigdb.org/Project:Study_lookup).

**Comment by lgeistlinger** [comment]
Can this be closed @lwaldron?

**Comment by lwaldron** [comment]
Yes, sorry about that! It looks great.
