### ISSUE TITLE
CSS not loading on all pages

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDB#103]
@tosfos

On all bugsigdb pages the stylesheet is not loading. Tested on three browsers (chrome, firefox, edge) on two computers using normal browsing and incognito/privacy mode as well as on a mobile device (Android). Confirmed by @lwaldron.

Examples:

![image](https://user-images.githubusercontent.com/13036789/133677200-abd79f04-90cf-41b9-afa4-ad4b175c350b.png)
![image](https://user-images.githubusercontent.com/13036789/133677215-83d42639-84b0-413e-9bee-762cb7a18dea.png)
![image](https://user-images.githubusercontent.com/13036789/133677551-a823310a-685d-4999-9030-fd8df896eed3.png)

**Comment by lwaldron** [comment]
Confirmed.

**Comment by tosfos** [comment]
We redeployed the image last night and everything looks good now. It's not clear why this happened. If it does happen again, we'll try and track down why.

**Comment by lgeistlinger** [comment]
Can confirm that things are back.
