### ISSUE TITLE
Glossary pages - add links to Studies

### ISSUE THREAD

**Issue by tosfos** [waldronlab/BugSigDB#105]
One side-effect that I notice is that these glossary pages dominate the simple search, e.g. see below for "cancer", of which some do and some don't appear in any Experiment. This might be disappointing to users when the glossary pages don't link further back to Study or Experiment pages (even in cases that that condition does appear in some experiments), leading them to think search results aren't relevant to bugsigdb.org. A couple possible workarounds I could think of are 1) exclude glossary terms from the simple search results, 2) use a semantic search (as in the drilldown) also in the simple search box. 

![image](https://user-images.githubusercontent.com/639942/140535727-f97188e9-de0d-4ea2-a189-f49e2e1430cd.png)

_Originally posted by @lwaldron in https://github.com/waldronlab/BugSigDB/issues/92#issuecomment-961995747_

**Comment by tosfos** [comment]
Instead of working around the issue, how about taking advantage of it? I think it would be cool to add functionality to the Glossary pages so that they would list all Studies that relate to this condition/body site and/or a link to a drilldown that will bring them to a filterable list of Studies on these conditions/body sites. That way, people who really are researching this particular condition or body site will get some useful content and links.

What do you think?

**Comment by lwaldron** [comment]
That sounds great! My only complaint was that the glossary pages were a
dead end, and that would turn them into ideal launching points instead…--

Levi Waldron

Associate Professor

Department of Epidemiology and Biostatistics

CUNY Graduate School of Public Health and Health Policy

Institute for Implementation Science in Population Health

55 W 125th St, New York NY 10035

https://waldronlab.io

Join the microbiome Virtual International Forum: https://microbiome-vif.org

**Comment by tosfos** [comment]
This is now done. Please review a sample of each Glossary type:

1. https://bugsigdb.org/Oral_gland
2. https://bugsigdb.org/Squamous_cell_carcinoma

**Comment by lgeistlinger** [comment]
This is fantastic! Just checked it out and it looks great. Thanks!

**Comment by lwaldron** [comment]
I love it!
