### ISSUE TITLE
duplicate studies

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#106]
I just noticed that:
* https://bugsigdb.org/Study_149
* https://bugsigdb.org/Study_345

are duplicates of the same PMID. One looks like a copy of the other, with some small differences in the signatures and taxon reviews, with one being all Wikiworks curator and editor. 

Not sure how this happened, but is there a way to search for duplicate studies, ie those with the same PMID?

**Comment by tosfos** [comment]
Yes, that should be possible.

**Comment by tosfos** [comment]
This is now ready for review. You can see a list of duplicates (and triplicates) [here](https://bugsigdb.org/Project:Duplicate_studies). We also linked to it from the [main Cleanup page](https://bugsigdb.org/Help:Cleanup#Duplicate_Studies).

![image](https://user-images.githubusercontent.com/10228795/143362167-1e6f309c-a022-478b-934d-0c41ce9931e6.png)

**Comment by lgeistlinger** [comment]
can this be closed @lwaldron?

**Comment by lwaldron** [comment]
I think so, although eventually we may want a system for clearing correct "duplicates" that are two different study designs from the same PMID, and have been reviewed as correct. When entering new studies, it's not clear to me yet when entering another study with the same PMID is allowed and when it isn't, see https://github.com/waldronlab/BugSigDB/issues/112.

**Comment by lgeistlinger** [comment]
@ftzohra22 I just wondered whether anyone ever went to the bottom of this and clarified whether [those](https://bugsigdb.org/Project:Duplicate_studies) are duplicates or not? Some look valid (ie different study designs indicating nested studies within studies), others look like clear duplicates such as eg PMID:30366118, and PMID:30568265.

**Comment by lgeistlinger** [comment]
Hi @ftzohra22 just checking back on the status of this?

**Comment by lwaldron** [comment]
The wiki is now correctly preventing duplicate PMIDs. Some of these appear to be curation errors with the same study entered with different ideas about design but that is a curation TODO.
