### ISSUE TITLE
Condition updates prompt creating + defining already existing glossary terms

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#107]
I edited the experiments of [Study 538](https://bugsigdb.org/Study_538) and changed the condition from the invalid "urinary track infection" to the valid condition glossary term [urinary tract infection](https://bugsigdb.org/Urinary_tract_infection).

However, when visiting the [updated page](https://bugsigdb.org/Study_538) the condition field of eg Experiment 1 does not recognize the existing condition glossary term [urinary tract infection](https://bugsigdb.org/Urinary_tract_infection) - as the term is marked in red and mousing over the term prompts me to "create and define glossary term". 

It does recognize it to a certain extent though, as the icon links beside the term point to the corresponding EFO page. BTW: I am confused about the icon beside the efo / uberon icon. It seems to point to the exact same pages and thus obsolete?

<img width="530" alt="Screen Shot 2021-11-25 at 1 09 31 PM" src="https://user-images.githubusercontent.com/11871050/143486614-568779d7-5ca5-4459-b18e-b85dd917243c.png">

**Comment by tosfos** [comment]
This is related to the issue I highlighted at https://github.com/waldronlab/BugSigDB/issues/92#issuecomment-968322051

It's caused by the wiki finding more than 1 matching Condition. Once we decide out how to deal with that situation, this should be resolved, but we should leave this open to make sure it gets solved.

**Comment by lgeistlinger** [comment]
Looks like this has been fixed and can be closed.

Remaining question:

>  BTW: I am confused about the icon beside the efo / uberon icon. It seems to point to the exact same pages and thus obsolete?

Should I open a separate issue for that?

**Comment by tosfos** [comment]
Sorry about the long delay. I agree that we should be able to combine these into one icon. I'll get back to you soon.

**Comment by lgeistlinger** [comment]
Thanks!

**Comment by tosfos** [comment]
Should be better now:
![image](https://user-images.githubusercontent.com/10228795/149836912-b6e05270-2d34-4a5a-80c1-b1ea34ab08b4.png)

**Comment by lgeistlinger** [comment]
Looks good, thanks!
