### ISSUE TITLE
How to find a study by PMID

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#109]
The simple search does not seem to find studies by PMID, for example [searching for 33440171](https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=33440171&go=Go) returns no results, even though this is the PMID for https://bugsigdb.org/Study_559. Searching for keywords from this abstract such as [synthetic enteral nutrition](https://bugsigdb.org/w/index.php?search=synthetic+enteral+nutrition&title=Special%3ASearch&profile=default&fulltext=1) also returns no results. I expected either of these searches to return Study_559.

**Comment by tosfos** [comment]
This looks like a general issue with the search index falling out of date. Will check.

**Comment by tosfos** [comment]
The search index issues have been resolved. We're still working on the underlying cause (server resources), but this can be closed.

**Comment by lgeistlinger** [comment]
Can confirm that those searches now return Study 559.
