### ISSUE TITLE
Advanced search could be more user-friendly

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#110]
1. the red "New Query" button on the main page would be more intuitive as "Advanced Search" or something like this. 
2. when I click on New Query, the mostly blank page doesn't make it very obvious how to get started, and the "Set up form" button on the right-hand side could easily be missed:
![image](https://user-images.githubusercontent.com/639942/149586478-c1b56d38-aea5-4263-a88d-7d4c4ccd4410.png)

**Comment by tosfos** [comment]
We took the following steps:

1. The text for the button on the main page has been changed to **Advanced Search**.
2. The form has been made visible on the query result page by default. No need to click **Set up form**.
3. A close control has been added to the form.
4. The Set up form button has been renamed to **Toggle form**.

Please let me know what you think about these changes.

**Comment by lwaldron** [comment]
The Advanced Search is good, I think this can be closed now.
