### ISSUE TITLE
EFO updates

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#113]
The UBERON ontology underlying body site annotation in BugSigDB seems to be stable, the last release is the [2019-11-22 release](https://uberon.github.io/).

This is not true for the Experimental Factor Ontology (EFO) underlying conditions annotated in BugSigDB, as the EFO publishes a [new release every month](https://github.com/EBISPOT/efo/releases).
Problematic for BugSigDB are updates to the ontology that involve changes of the term name -> term ID mapping, which have the potential to invalidate

1) links to the EFO for conditions on BugSigDB's experiment sites and glossary term sites,
2) mappings from condition to EFO ID in the exported experiment.csv.

An example is the latest [EFO 3.38.0 release](https://github.com/EBISPOT/efo/releases/tag/v3.38.0) that involves remapping of certain EFO terms to existing MONDO terms. 
As a result, certain conditions annotated in BugSigDB such as

[schizophrenia](https://bugsigdb.org/Schizophrenia)
[type II diabetes mellitus](https://bugsigdb.org/Type_II_diabetes_mellitus)
[multiple sclerosis](https://bugsigdb.org/Multiple_sclerosis) 

are now pointing to obsolete terms in the EFO, as those have been replaced with a corresponding MONDO term (see eg [here](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0003885)). I think that is fine for the moment, but we might want to start thinking about adapting a periodic update scheme for the condition to EFO mapping in the future.

**Comment by lwaldron** [comment]
Interesting - I couldn't find some universal list of aliases and obsolete terms like HGNC maintains, but this information seems embedded in the ontology itself.  Looping in @tosfos.

**Comment by tosfos** [comment]
> we might want to start thinking about adapting a periodic update scheme for the condition to EFO mapping in the future

I agree that this is probably the best way to go. We can create a script to automatically check the links and grab the replacement term.

**Comment by lgeistlinger** [comment]
> We can create a script to automatically check the links and grab the replacement term.

That would be great if this figures to be feasible. This would also be simpler than re-importing from the obo/owl files accompanying each release I believe.

**Comment by tosfos** [comment]
The script is now complete and active. It works really well! You can see an example [here](https://bugsigdb.org/w/index.php?title=Schizophrenia&type=revision&diff=78651&oldid=47044).

And we were actually able to cover instances that were not in the original spec. For example, [this](https://bugsigdb.org/Puumala_virus) page referenced [this](http://purl.obolibrary.org/obo/NCBITaxon_11604) link, which is completely invalid for some reason. But our script replaced it with [this](http://purl.obolibrary.org/obo/NCBITaxon_1980486) appropriate link anyway. I assume this is desired behavior.

The script has made [over 1,000 changes](https://bugsigdb.org/w/index.php?limit=200&days=90&enhanced=1&title=Special:RecentChanges&urlversion=2) so far. There is thing I'm wondering about though. Apparently as part of the import were pages that actually were obsolete and have "obsolete" in the title. [Here](https://bugsigdb.org/Obsolete_abdomen) is an example. Our script, of course, went ahead and updated the link to the non-obsolete term. Is that a good thing?

**Comment by lgeistlinger** [comment]
I love it! Will these updates also manifest in the exported experiments.csv in the EFO ID column? That would be great.

> But our script replaced it with this appropriate link anyway. I assume this is desired behavior.

Yes. This looks like an erroneous link in the EFO OBO file from which I extracted the import table for the glossary; so it's a good thing that these seem to get fixed as a side effect.

> Apparently as part of the import were pages that actually were obsolete and have "obsolete" in the title.

I don't think they hurt much (as I don't assume curators to actually pick an obsolete term as body site / condition), but strictly speaking I believe we should remove terms with an "^obsolete_" in the title from the glossary entirely to avoid curators picking those by accident.

**Comment by tosfos** [comment]
> Will these updates also manifest in the exported experiments.csv in the EFO ID column?

Yes it will! We do need to do a data rebuild (or similar) first. We'll check.

> I believe we should remove terms with an "^obsolete_" in the title from the glossary entirely to avoid curators picking those by accident.

Will do.

**Comment by tosfos** [comment]
We verified that no pages currently list an obsolete term (a Glossary page with "obsolete" starting the page name). We'll delete them.

**Comment by lgeistlinger** [comment]
Perfect

**Comment by tosfos** [comment]
Done. All 988 obsolete terms have been deleted. The property update is in progress.

We also added some code so that the CSV export field will get updated automatically in the future.

I believe this can be close.

**Comment by lgeistlinger** [comment]
Looking great! Many thanks!!
