### ISSUE TITLE
general wiki performance

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#115]
General wiki performance has been spotty. Here is an uptime robot measuring load time for a randomly selected but rather large Study page (https://bugsigdb.org/Study_428), monitoring load time. First load time was 21s: https://stats.uptimerobot.com/v85AvUWYnA/790659101

**Comment by lwaldron** [comment]
I'm subjectively noticing an improvement in page load times, and the Study 428 uptime robot is down to ~12s average load time.

**Comment by tosfos** [comment]
We are beginning the process of migrating to a new, larger Azure VM.

**Comment by kbeckenrode** [comment]
I looked at the front page and it looks great! I like the featured sections 👍 But I didn't see any typos, and the links embedded for more information is great. 10/10

**Comment by tosfos** [comment]
We're ready to switch to the new server. Please confirm that we can go ahead with this @lwaldron . Thanks

**Comment by lwaldron** [comment]
OK with me.--

Levi Waldron

Associate Professor

Department of Epidemiology and Biostatistics

CUNY Graduate School of Public Health and Health Policy

Institute for Implementation Science in Population Health

55 W 125th St, New York NY 10035

https://waldronlab.io

Join the microbiome Virtual International Forum: https://microbiome-vif.org

**Comment by tosfos** [comment]
We have this scheduled for this Saturday night/Sunday morning, overnight US time.

**Comment by lgeistlinger** [comment]
I think this can be closed.
