### ISSUE TITLE
Human (not bot) recent changes include WikiWorks753 edits

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#116]
I assume these should be filtered by the `Human (not bot)` filter? Or is there another filter we can add so that WikiWorks753 edits don't dominate?

https://bugsigdb.org/Special:RecentChanges?hidebots=1&limit=100&days=30&enhanced=1&urlversion=2

**Comment by tosfos** [comment]
Fixed.

**Comment by tosfos** [comment]
Can this be closed?

**Comment by lwaldron** [comment]
Yes
