### ISSUE TITLE
table of top contributors

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#117]
It would be nice to have a table of the most active contributors over various time periods, such as https://www.mixesdb.com/db/index.php?title=Special:ContributionScores. Would be great if there is an extension that can work without too much customization.

**Comment by tosfos** [comment]
We installed that extension [here](https://bugsigdb.org/Special:ContributionScores). We still need to do some work to figure out why it's including some of the WikiWorks users:
![image](https://user-images.githubusercontent.com/10228795/156830880-64c01776-d3a2-4922-bee9-3c1778760fba.png)

Please let me know if this looks good. We can also include this list on the Main Page if you'd like. We can set it to X number of contributors in the last Y number of days. Please let me know.

**Comment by lwaldron** [comment]
It looks great! I'm guessing the Wikiworks bot showing up is related to #116, and could be addressed there. How about putting the top 5 contributors in the last 30 days on the front page, with a link to the full table of contributors? This will help highlight that this is a community-editable wiki, and give credit to active contributors.

**Comment by tosfos** [comment]
I don't think this is related to #116. It's likely a bug in the extension. I don't think it will affect the Main Page display though. Please let me know if we should research this further.

**Comment by lwaldron** [comment]
I don’t think it’s significant enough to need further research.--

Levi Waldron

Associate Professor

Department of Epidemiology and Biostatistics

CUNY Graduate School of Public Health and Health Policy

Institute for Implementation Science in Population Health

55 W 125th St, New York NY 10035

https://waldronlab.io

Join the microbiome Virtual International Forum: https://microbiome-vif.org

**Comment by lwaldron** [comment]
Saw it on the front page, looks great!
