### ISSUE TITLE
"Download CSV" from Advanced Search returns no rows of data

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#119]
For example here is a [search for total skin](https://bugsigdb.org/Special:RunQuery/Drill?Drill=Condition%2Blogic%3DAND%26Location%2Blogic%3DAND%26Site%2Blogic%3DAND&_run=1&title=Special%3ARunQuery%2FDrill&pfRunQueryFormName=Drill&Drill%5BTaxon%5D%5Bis_list%5D=1&Drill%5BLocation+of+subjects%5D%5Bis_list%5D=1&Drill%5BLocation+logic%5D=AND&Drill%5BHost+species%5D%5Bis_list%5D=1&Drill%5BBody+site%5D%5B%5D=entire+skin&Drill%5BBody+site%5D%5Bis_list%5D=1&Drill%5BSite+logic%5D=AND&Drill%5BCondition%5D%5Bis_list%5D=1&Drill%5BCondition+logic%5D=AND&Drill%5BNCBI%5D=&wpRunQuery=Run+query&pf_free_text=). 	When I click Download CSV for Studies, Experiments, or Signatures, I get a file with a header row but no rows of data (see attached).

[signatures-filtered-20220221.csv](https://github.com/waldronlab/BugSigDB/files/8108320/signatures-filtered-20220221.csv)
[experiments-filtered-20220221.csv](https://github.com/waldronlab/BugSigDB/files/8108321/experiments-filtered-20220221.csv)
[studies-filtered-20220221.csv](https://github.com/waldronlab/BugSigDB/files/8108322/studies-filtered-20220221.csv)

**Comment by seandavi** [comment]
Related, but what is the relationship between the links on the website to the data living in the github repo?

**Comment by lwaldron** [comment]
> Perhaps unrelated, but what is the relationship between the links on the website to the data living in the github repo?

Files living at https://github.com/waldronlab/bugsigdbexports are created by bugsigdbr, based on its imports from https://bugsigdb.org/Help:Export. I haven't directly compared, but I assume these focused CSV exports are just subsets of the full exports provided at https://bugsigdb.org/Help:Export.

**Comment by tosfos** [comment]
This issue should be resolved now.

**Comment by lwaldron** [comment]
Confirmed, thanks @tosfos. Should there be an associated commit, or is the fix made somewhere else?

**Comment by tosfos** [comment]
The fix was within the wiki template itself. [Here](https://bugsigdb.org/w/index.php?title=Template:Drill&diff=prev&oldid=79481)'s the diff if you'd like to see it.

**Comment by lwaldron** [comment]
Got it!
