### ISSUE TITLE
Alpha diversity should not be hidden from experiments

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#120]
Since Alpha diversity is a result and not a method, ideally it would be shown for every Experiment even if it is repeated from above. For example, see Experiment 3 at https://bugsigdb.org/Study_568. It is hidden here that Shannon and Simpson are increased, and Chao1 is unchanged.

**Comment by tosfos** [comment]
This should be complete. Please review.

**Comment by lwaldron** [comment]
Looks good!
