### ISSUE TITLE
Some glossary terms do not have a "Studies related to" 

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#122]
I find the "Studies related to" feature on glossary terms such as [HIV infection](https://bugsigdb.org/HIV_infection) very useful as it allows to quickly identify the studies investigating a certain condition.

I was wondering why some glossary terms such as [colorectal cancer](https://bugsigdb.org/Colorectal_cancer) and [autism](https://bugsigdb.org/Autism) do not have this feature although we have studies investigating them, eg

[Study 470](https://bugsigdb.org/Study_470), [Study 471](https://bugsigdb.org/Study_471), and [Study 202](https://bugsigdb.org/Study_202).

**Comment by tosfos** [comment]
We're in the middle of reworking this system as part of #111 . It is strange that those Studies aren't being shown. We'll check if this is resolved once the other issue is complete.

**Comment by tosfos** [comment]
Looking good now!

**Comment by lgeistlinger** [comment]
Great, thanks!
