### ISSUE TITLE
Several studies have incorrect journal name "REFERENCES" or "References"

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDB#125]
I thought this might be an issue with the import from the spreadsheet but it's also happening to a few newer studies.

For examples see:
https://bugsigdb.org/Study_523 (should be AJRI)
https://bugsigdb.org/Study_400 (should be PAI)
https://bugsigdb.org/Study_343 (should be Cancer)

**Comment by tosfos** [comment]
This looks like an issue on the PubMed side. We'll check.

**Comment by tosfos** [comment]
This was due to a bug in the PubMed extension we're using. We patched the bug and we'll be updating the server to use the new version shortly.

**Comment by lwaldron** [comment]
These examples all display correctly now. Thanks for reporting @cmirzayi!
