### ISSUE TITLE
Experiment number doesn't get updated once an experiment is deleted

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDB#126]
While creating a 2nd experiment today on https://bugsigdb.org/Study_516# it was taking a while to save the new entry so i clicked on save twice. It turns out two experiments were created due to my double clicks and I deleted the duplicate one. I deleted experiment 2 instead of 3. So now the page has Experiment 1 and then Experiment 3. I assumed once an experiment is deleted the next one would automatically update to match the number in order. Is there a way to do this so that during analysis it doesn't seem like an experiment is missing?

**Comment by tosfos** [comment]
We fixed this via page move. I don't assume this is worth worrying about since it shouldn't happen too often.

**Comment by lwaldron** [comment]
Thanks @tosfos. Agreed, under most other circumstances URLs should remain fixed even if an experiment is deleted and creates a gap.
