### ISSUE TITLE
slow loading and editing for Study 618

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#127]
I'm seeing very slow load times (at least minutes, and seeing 504 Gateway Time-outs) for https://bugsigdb.org/Study_618, even though other pages are OK. I started noticing this slow load time after adding a taxon review to a Study 618 signature, not sure if that is related.

**Comment by lwaldron** [comment]
FYI @ftzohra22

**Comment by lwaldron** [comment]
I confirmed that https://bugsigdb.org/Study_618 remains unavailable today. I also tried editing another signature (https://bugsigdb.org/Study_386/Experiment_1/Signature_2) by correcting the three non-NCBI elements, but when I clicked "Save" I just eventually got the 504 Gateway Time-out, and now https://bugsigdb.org/Study_386 is also unavailable.

**Comment by tosfos** [comment]
We'll check

**Comment by tosfos** [comment]
This was some sort of docker issue that was resolved by a restart. You may see slower performance while the caches warm up. This issue is resolved.

**Comment by lwaldron** [comment]
Confirmed back to normal.
