### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#13]
I noted 2 things here:

1. In the edit / add a experiment forms, the tooltip for "host species" displays the tooltip for "confounding factors"

2. The tooltip for "Richness" (section "Alpha diversity") is missing and should be: "Number of species"

> Ike: Note that we did not receive descriptions for all of the fields but they can be added.

I confirm that tooltips for study and signature fields are currently missing and I will provide those as well.

**Comment by tosfos** [comment]
@lwaldron Should anything be done here?

**Comment by lwaldron** [comment]
Yes go ahead, just one small edit. Instead of:
> If autocomplete does not find the name of the taxon, enter a numeric NCBI taxon identifier by searching [here](link)

This would be more helpful;
> Autocomplete is only aware of names already in bugsigdb. If it does not find the name of the taxon, enter a numeric NCBI taxon identifier by searching [here](link)

**Comment by tosfos** [comment]
> This would be more helpful

This is done, @lwaldron . Please review [here](https://bugsigdb.org/Special:FormEdit/Signature/test).

**Comment by tosfos** [comment]
Is our assistance needed at all for this task @lgeistlinger ? Please let me know.

**Comment by lgeistlinger** [comment]
I am going to collect all the remaining tooltips, partly referenced in separate issues above (eg antibiotics exclusion, case definition, completion status) and post them here.

If it's straightforward to add them to the wiki, I can do it myself, otherwise I'd ask for your help @tosfos.

**Comment by tosfos** [comment]
Sounds good! Please feel free to reach out.

**Comment by lgeistlinger** [comment]
Hi @tosfos:

Action points here would be to update the tooltips as follows:

- Antibiotics exclusion: `Number of days without antibiotics usage (if applicable) and other antibiotics-related criteria used to exclude participants (if any)`
- Group 1 definition: `Diagnostic criteria applied to define the specific condition / phenotype represented in the case (exposed) group`
- Form Data -> This form's data is: complete/incomplete: `Mark as incomplete to complete the form at a later time. Mark as complete to submit the page to a reviewer.`

**Comment by lgeistlinger** [comment]
Just wanted to check in whether we are all set for this one or whether additional input / actions from my side are needed?

**Comment by tosfos** [comment]
Sorry. I wasn't assigned to this so I wasn't checking it. Will do.

**Comment by lgeistlinger** [comment]
Looks like those have already been included on the page. Closing. Thanks @tosfos!
