### ISSUE TITLE
Add keywords to abstract section

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#130]
I noticed that when the PubMed abstract is in a structured format (ie in several sections), only the first section is shown in bugsigdb.org. This effects quite a few studies, so probably worth fixing. Here is what I found from looking through the first 20 search results for ["BACKGROUND"](https://bugsigdb.org/w/index.php?title=_Special:Search&search=%22BACKGROUND%3A%22&go=Go&searchToken=4i0pq7bhr9vxjxj4lxqy222y).

Only the first section is imported (most look like this - I included all from the first page of results since I was browsing them anyways, but no need to look at them all...):
- https://bugsigdb.org/Study_1
- https://bugsigdb.org/Study_21
- https://bugsigdb.org/Study_46
- https://bugsigdb.org/Study_78
- https://bugsigdb.org/Study_95
- https://bugsigdb.org/Study_113
- https://bugsigdb.org/Study_114
- https://bugsigdb.org/Study_128
- https://bugsigdb.org/Study_214
- https://bugsigdb.org/Study_176
- https://bugsigdb.org/Study_296
- https://bugsigdb.org/Study_321
- https://bugsigdb.org/Study_368
- https://bugsigdb.org/Study_391
- https://bugsigdb.org/Study_407
- https://bugsigdb.org/Study_532

These studies use different section titles than most:
- https://bugsigdb.org/Study_288 (this one has unusually poorly-named section headings, showing only that these can be anything)
- https://bugsigdb.org/Study_98
- https://bugsigdb.org/Study_65
- https://bugsigdb.org/Study_49
- https://bugsigdb.org/Study_78

Complete but displayed in a different font and formatting (not terrible, just a little odd):
- https://bugsigdb.org/Study_351
- https://bugsigdb.org/Study_362 

Doesn't have line-breaks between sections, but this is OK, even if all structured abstracts were like this (but it looks like the PubMed abstract is like this too, without line-breaks):
- https://bugsigdb.org/Study_363

If patching the PUBMED module we're using, it might be nice to also show the keywords that come with each abstract too (not key, just nice)...

**Comment by tosfos** [comment]
This is now done. Performance may suffer a bit while the caches warm up.

**Comment by tosfos** [comment]
> These studies use different section titles than most:

That is likely just what PubMed is sending us.

> Complete but displayed in a different font and formatting (not terrible, just a little odd):

That is likely due to PubMed including some extra whitespace. We'll see if we can trim it.

> Doesn't have line-breaks between sections, but this is OK, even if all structured abstracts were like this (but it looks like the PubMed abstract is like this too, without line-breaks):

Yes, the PubMed data is probably missing line-breaks.

> it might be nice to also show the keywords that come with each abstract too

We should be able to do that.

**Comment by tosfos** [comment]
We're ready to start displaying the keywords. How should they be displayed? I think they should go as a list after the Year in the Study infobox. Please let me know what you think.

**Comment by tosfos** [comment]
Also, should the Keywords list be included in the CSV export?

**Comment by lwaldron** [comment]
I'm not sure about either of those things. As for exporting Keywords list, I guess I would say "why not?" If it's there, someone will probably figure out how to use it...

**Comment by tosfos** [comment]
> Complete but displayed in a different font and formatting

Fixed

**Comment by lwaldron** [comment]
Looks good!

**Comment by tosfos** [comment]
Reopening. We never actually implemented keywords here. Is that desired?

**Comment by tosfos** [comment]
Can we apply this to production?

**Comment by lwaldron** [comment]
I don't see why not, although I noticed the keywords was only filled for the first of the 10 studies in the example you provided? Keyword filter on the Drilldown sounds nice, if we are getting them for most/all studies.

**Comment by tosfos** [comment]
> I don't see why not, although I noticed the keywords was only filled for the first of the 10 studies in the example you provided?

Oops! It looks like the data was still populating when I downloaded the CSV. This should be better:

[Keyword sample.csv](https://github.com/waldronlab/BugSigDB/files/11791383/Keyword.sample.csv)

We'll go ahead and apply it to production.

**Comment by tosfos** [comment]
This is done. [Here](https://bugsigdb.org/Study_2) is an example. The [CSVs](https://bugsigdb.org/Special:Ask/-5B-5BCategory:Studies-5D-5D/-3FStudy-20design/-3FPMID/-3FDOI/-3FURL/-3FAuthors-20list/-3FTitle/-3FJournal/-3FYear/-3FAbstract/-3FKeyword-20list%3DKeywords/-3FState/-3FReviewer/mainlabel%3DStudy-20page-20name/limit%3D5000/order%3Dasc/sort%3DPage-20sort-20number/offset%3D0/format%3Dcsv/searchlabel%3DDownload-20all-20Studies-20(CSV)/filename%3Dstudies.csv) also appear to have populated with all the available keyword data.

**Comment by tosfos** [comment]
Can this be closed?

**Comment by lwaldron** [comment]
Yes, looks great!
