### ISSUE TITLE
Page 'reviewed' sometimes not updating

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDB#132]
This happened with a couple papers I was reviewing today. When I click on the mark reviewed button it turned to 'flag for review' without the information displaying the page has been 'reviewed', Refreshing the page doesn't solve the issue either. It's only working if I flag it for review again then mark it as reviewed.
![image](https://user-images.githubusercontent.com/45443641/161931310-78157d53-c95f-4c7a-b573-b2974da5a3bf.png)

**Comment by lwaldron** [comment]
@ftzohra22 can you provide a link to the Study?

**Comment by ftzohra22** [comment]
Sorry I fixed that one but here's another example: Experiment 2, Signature 2  ( https://bugsigdb.org/Study_428# )

**Comment by lwaldron** [comment]
I think this related to #131 - when you click "mark as reviewed", the change occurs internally but your window doesn't refresh, like we see in the screenshot below including both @ftzohra22 's and my screens, where my newly navigated window shows a review but @ftzohra22, who marked this signature reviewed, does not. I think that's fine for the page to be unrefreshed as long as we know to expect it. 

![image](https://user-images.githubusercontent.com/639942/161988086-283545df-9148-4953-a850-e8b39035b765.png)

**Comment by lwaldron** [comment]
@ftzohra22 do you know if this was just a matter of the page only showing the review after refreshing? If that's all it is I think we'll close the issue without change, since we are now avoiding refreshing the page after review to speed up reviewing.

**Comment by ftzohra22** [comment]
Yes I think that was it. It was taking too long for the 'review' status to get updated unless refreshed and looks like its working fine now. We can close the issue.

**Comment by tosfos** [comment]
This issue is closed, but noting that we added a follow-up with improved visuals for after the Review button is clicked. Feel fee to create an issue if any changes are needed.
