### ISSUE TITLE
make Study information editable

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#133]
Currently the only way to create study information like title, authors, abstract, etc is to import a study from PubMed. But we can have signatures that don't originate from PubMed, for example https://bugsigdb.org/Study_562. Can you make it possible to edit Study information manually? 

I'm not sure whether it should be editable for all studies, or only non-PubMed studies - off the top of my head I'm thinking for all studies, and the PubMed module is just a convenience for filling them automatically when a study happens to be in PubMed.

**Comment by tosfos** [comment]
This is now possible. I think you've already seen the manual/automatic option.

**Comment by lwaldron** [comment]
Yes it works great!
