### ISSUE TITLE
Update which autocomplete values are editable

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#135]
The page https://bugsigdb.org/Help:Admin has links to modify forms' autocomplete values, but some of these (such as "Matched on" and "Confounders controlled for") now use built-in ontologies instead of being editable. Could you check these @rimsha1 and remove links that do not lead to a page where you can edit the values?

- [ ] [16S variable region](https://bugsigdb.org/w/index.php?title=Property:16S_variable_region/Values&action=edit)
- [ ] [Body site](https://bugsigdb.org/w/index.php?title=Property:Body_site/Values&action=edit)
- [ ] [Condition](https://bugsigdb.org/w/index.php?title=Property:Condition/Values&action=edit)
- [ ] [Confounders controlled for](https://bugsigdb.org/w/index.php?title=Property:Confounders_controlled_for/Values&action=edit)
- [ ] [Curator](https://bugsigdb.org/w/index.php?title=Property:Curator/Values&action=edit)
- [ ] [Host species](https://bugsigdb.org/w/index.php?title=Property:Host_species/Values&action=edit)
- [ ] [Location of subjects](https://bugsigdb.org/w/index.php?title=Property:Location_of_subjects/Values&action=edit)
- [ ] [Matched on](https://bugsigdb.org/w/index.php?title=Property:Matched_on/Values&action=edit)
- [ ] [Sequencing platform](https://bugsigdb.org/w/index.php?title=Property:Sequencing_platform/Values&action=edit)
- [ ] [Sequencing type](https://bugsigdb.org/w/index.php?title=Property:Sequencing_type/Values&action=edit)
- [ ] [Statistical test](https://bugsigdb.org/w/index.php?title=Property:Statistical_test/Values&action=edit)
- [ ] [Study design](https://bugsigdb.org/w/index.php?title=Property:Study_design/Values&action=edit)

**Comment by lwaldron** [comment]
@tosfos I have a question for you too here. There was a page processing error for the HDL item under "Confounders controlled for" at https://bugsigdb.org/Study_20/Experiment_1. Looking [here](https://bugsigdb.org/w/index.php?title=Property:Confounders_controlled_for/Values&action=edit) I see `{{:Property:Condition/Values}}`, which I think means these terms should be chosen from the "Condition" values, which are EFO. So I found and entered the term [HDL cholesterol change measurement](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0007805) from EFO, but this is still a page processing error. What should I do to correctly record that changes in HDL cholesterol were controlled for?

**Comment by lwaldron** [comment]
Never mind @tosfos , I remembered that the [Condition](https://bugsigdb.org/w/index.php?title=Property:Condition/Values&action=edit) values are also manually maintained. It is OK that way. @rimsha1 that means that, for example, Confounders controlled for should just link to the same link that Condition links to (https://bugsigdb.org/w/index.php?title=Property:Condition/Values&action=edit).

**Comment by lwaldron** [comment]
@ftzohra22 I just wanted to alert you also to this procedure, since you are also reviewing. You can correct invalid terms or if needed edit the allowed values, trying to use the relevant ontology (Uberon or EFO).

**Comment by lwaldron** [comment]
Pinging @rimsha1 @ftzohra22

**Comment by rimsha1** [comment]
Hi @lwaldron I am trying to understand this **"Confounders controlled for should just link to the same link that Condition links to"** Confounders controlled for already links to the values that condition has. Do you want confounders to have its own editable values?

**Comment by lgeistlinger** [comment]
Seems like this has been resolved. Re-open as needed.
