### ISSUE TITLE
LinkML for validating ontologies

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#136]
I recently became aware of the LinkML (https://linkml.io/) project for modeling and validating data. We may want to consider it as an alternative to having to import and maintain ontologies in bugsigdb.org, because a LinkML data model can for example, specify that an entry must belong to the Experimental Factory Ontology, and their validation tool can check that automatically without having to implement ontology validation locally. LinkML is an actively developed project eager to collaborate and I've met a couple of their developers, so it may also be worth thinking about a Semantic MediaWiki extension that could take advantage of their infrastructure more generally than just our use cases.

**Comment by tosfos** [comment]
Sounds cool. Would be an exciting project and should be doable.

**Comment by tosfos** [comment]
What's the status here, please?

**Comment by lgeistlinger** [comment]
Closing this until further notice
