### ISSUE TITLE
Reviewed studies still on 'missing review' list

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDB#137]
@tosfos The 'missing review' list seems to be not updating. For reference: Study 496, 482, 511 (https://bugsigdb.org/Study_469 https://bugsigdb.org/Study_511) were all reviewed over a week ago and are still on the list. I'm not sure how long it usually takes for a study to be cleared from the list after being marked reviewed but looks like as of now reviewed studies are all still listed there.

**Comment by tosfos** [comment]
We'll check.

**Comment by ftzohra22** [comment]
Thank you. Generally how long does it take for them to clear from the list?

**Comment by tosfos** [comment]
It should be within a minute, but occasionally may take longer if the server is busy.

**Comment by tosfos** [comment]
Can this be closed?
