### ISSUE TITLE
Add Bioconductor logo

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#140]
Would you add a Bioconductor logo next to the SPH logo? From https://bioconductor.org/about/logo/

**Comment by tosfos** [comment]
![image](https://user-images.githubusercontent.com/10228795/175398572-f8d65168-ff21-45de-a46a-07ccae2a52d1.png)

Please let me know if this looks good.

**Comment by lwaldron** [comment]
Yes, looks good!
