### ISSUE TITLE
Field name "location of subjects" not upating with validated term

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDB#144]
"Indonesia" was added as a validated location of study a week ago but still isn't showing up on the suggested country list, Given this field is not a free entry form it's not also possible to enter it.

**Comment by lwaldron** [comment]
Confirmed, I see Indonesia among the Location_of_subjects values
<https://bugsigdb.org/Property:Location_of_subjects/Values> but can't add
it as a location in an Experiment. We should replace these values with a
more comprehensive list of countries, such as from the FAO ontology (
https://en.wikipedia.org/wiki/Geopolitical_ontology).

**Comment by tosfos** [comment]
This is a bug of some sort in the extension. It stems from some changes we made to help the autocomplete values load faster. We're going to try an alternative autocomplete method that should help.

**Comment by tosfos** [comment]
Done. This can be closed.
