### ISSUE TITLE
Condition pages not updating on edit to experiments

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#146]
An irritable bowel syndrome (IBS) study "[The microbiome of the oral mucosa in irritable bowel syndrome](https://bugsigdb.org/Study_57)" was incorrectly recorded as inflammatory bowel disease (IBD), so I corrected the condition yesterday in both its experiments. But the study still does not appear in https://bugsigdb.org/Irritable_bowel_syndrome, and still does appear in https://bugsigdb.org/Inflammatory_bowel_disease where it should no longer appear. This kind of error and correction is hopefully pretty rare, but can happen.

**Comment by tosfos** [comment]
Looks like it updated itself, likely within a few hours. We'll check if we can improve on that.

**Comment by tosfos** [comment]
Noting that we were able to improve the update speed for the page to be listed in the updated Condition page. We don't currently have a good way to update the previous Condition page, so it may take a bit of time to be removed from there.
