### ISSUE TITLE
Missing terms of service

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/BugSigDB#147]
When creating an account: "Make sure that you first read the [Terms of Service](https://bugsigdb.org/w/index.php?title=Project:Terms_of_Service&action=edit&redlink=1) before requesting an account." But the link doesn't contain the terms of service: https://bugsigdb.org/Project:Terms_of_Service.

**Comment by lwaldron** [comment]
Thanks Samuel, I just saw this.

**Comment by lgeistlinger** [comment]
Are we going to add terms of service here or can this be closed?

**Comment by lgeistlinger** [comment]
@lwaldron
