### ISSUE TITLE
Strict checking of vocabulary-controlled fields

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#148]
Body site, Sequencing platform, and Statistical test currently allow free-form entry even though we have lists of allowed values. Here is an example: https://bugsigdb.org/Study_563/Experiment_2

Can we lock these down to only allow use of the allowed vocabulary? I saw a curator who had entered mixed-capitalization of the Condition field this summer but had already corrected it, and I wasn't able to free-form Condition, so I guess this has since been locked down?

**Comment by tosfos** [comment]
Will do

**Comment by tosfos** [comment]
We restricted these fields:
1. Body site
2. Condition
3. Sequencing platform
4. Statistical test

Please review and close if it looks good.

**Comment by ftzohra22** [comment]
@lwaldron @tosfos It seems like the condition field is sometimes not auto-filling data from the ontology site/condition page (please check screenshot below). "Irritable bowel syndrome" is a valid EFO term as well as listed on our condition page but shows no results found. Given that this field is restricted, I'm also unable to enter it as free text. We've run into this issue once before with 'Huntington disease' but it was fixed the next day so I didn't bring it up. 
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/45443641/196949090-b28c7947-e7b8-4c9b-afda-9ab6be629a20.png">

**Comment by lwaldron** [comment]
I confirm I also see the same as @ftzohra22

**Comment by tosfos** [comment]
We've been struggling with this type of issue for a while. Ultimately it looks like a PageForms bug. And indeed there's a note in the code internals that mentions that the feature will struggle with a large set of autocomplete values. We're going to spend some time on a full solution.

**Comment by lgeistlinger** [comment]
Just noting that I experience the same for the body site field when eg trying to enter an existing term "buccal mucosa":
<img width="696" alt="Screen Shot 2022-10-22 at 10 54 49 AM" src="https://user-images.githubusercontent.com/11871050/197345973-a19709bb-f7b2-4f02-b850-c6dd04e20293.png">

**Comment by lwaldron** [comment]
I hear this is interfering with curation, so is there some temporary workaround if the proper solution will take a while?

**Comment by lwaldron** [comment]
I heard this is interfering with curation, so is there some temporary workaround if the proper solution will take a while?

**Comment by tosfos** [comment]
We'll check. I also bumped up the priority for this task.

**Comment by lgeistlinger** [comment]
Hi @tosfos just wondering what is the status of this one?

**Comment by lgeistlinger** [comment]
This would be a priority for us as it precedes other clean-up of eg body sites in #151

**Comment by lwaldron** [comment]
Agreed, this should be top priority because it is still interfering with curation.

**Comment by tosfos** [comment]
We've been waiting for the script that's resolving #111 to complete. That script does look done now, so we'll move forward on this.

**Comment by tosfos** [comment]
We believe things should be much improved. Please test and let us know what you find.

**Comment by lgeistlinger** [comment]
Can confirm - tested the terms that gave issues above and autocomplete would show up fast with these terms. Can we remove the note "Due to a temporary issue, autocomplete may not load the full list of possible options." from the entry form @tosfos? This can then be closed.

**Comment by ftzohra22** [comment]
Checked and can confirm its working
<img width="956" alt="image" src="https://user-images.githubusercontent.com/45443641/207622047-2245440b-1b7a-4c12-8ff6-369b6c260183.png">

**Comment by tosfos** [comment]
That's great news! Removed the warning on both Experiments and Signatures.
