### ISSUE TITLE
remove forum extension (was: enable forum extension)

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#150]
Could we create some kind of forum for discussion of issues site-wide? We are currently using Slack for this but I'd like to migrate some of our discussion to the wiki as a way to a) encourage curators and reviewers to interact more frequently with bugsigdb.org, and b) open these discussions up to the public as we start to try to build a wider community of users. It would be great for users to see notifications of new activity in the forum, both in the Notifications or Alerts icon, and by email (the option to reply by email would be very convenient).

The user forum should be linked to from the main page.

**Comment by tosfos** [comment]
Will do

**Comment by tosfos** [comment]
The forum can be accessed [here](https://bugsigdb.org/Special:WikiForum). Once it's set up, please let me know and we will add a link on the Main Page. Once there is content, we can show the most recent threads in the forums, which should probably also be included on the Main Page.

> It would be great for users to see notifications of new activity in the forum, both in the Notifications or Alerts icon, and by email (the option to reply by email would be very convenient).

It does not look like this ability is currently possible with the extension. Should we research adding these features?

**Comment by lwaldron** [comment]
@ftzohra22 would you set this up and see whether it could feasibly replace our curator Slack channel with it?

**Comment by ftzohra22** [comment]
Yes will do

**Comment by ftzohra22** [comment]
@tosfos @lwaldron could we please add the option to 'watch' the forum page? That way users can be notified if there is a new thread of discussion added to the forum. 
https://bugsigdb.org/Special:WikiForum

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/45443641/200809528-f1ca0250-60b4-4fbc-bc87-ea69f7ab5637.png">

**Comment by lwaldron** [comment]
Concur with Fatima's request - I think it will be hard to use a forum without being able to receive email or watchlist notifications about new messages. I would also be content with linking to an external service like Google Groups, which could have the advantage of a quicker sign-up process for people who don't yet have a wiki account. Thoughts?

**Comment by tosfos** [comment]
We will research adding notifications to the forum. We can link to Google Groups and also allow people to sign in with a Google account.

**Comment by tosfos** [comment]
We can add basic notifications to the forum extension. We estimate around 10 hours.

We can also enable sign-in with Google and it shouldn't be too difficult. Please advise on how to proceed.

**Comment by tosfos** [comment]
Where should we link to that Google Group?

**Comment by lwaldron** [comment]
It should be enough to link to it on pages that I can edit myself. @Fatima
Zohra ***@***.***> thoughts? If we go this route we should
probably de-activate the existing forum.

**Comment by tosfos** [comment]
You may have noticed that you can now log in with a Google account:
![image](https://user-images.githubusercontent.com/10228795/215380358-4832f0ca-58e1-475e-a483-89c9c8a32797.png)

The way it works is that you need to create an account the normal way. If that account is associated with a Google account as the email address, you can use that account to log in to the wiki. We do have an option of allowing account creation via Google account directly, but that is much more involved and requires some discussion if you'd like to move forward with that.

**Comment by lwaldron** [comment]
It works for me! We can revisit later if we decide we want to allow account creation via Google.

**Comment by lwaldron** [comment]
Opening again to request disabling of the WikiForum extension, as we are going to use https://groups.google.com/g/bugsigdb instead. Sorry about that.

**Comment by tosfos** [comment]
[Removed](https://bugsigdb.org/Special:Version). Closing.
