### ISSUE TITLE
Body site review

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#151]
@claregri @ftzohra22  from the review of body sites in BugSigDB, it figures that some review + clean up is needed on studies annotated with the following sites:
- [oral gland](https://bugsigdb.org/Oral_gland): these studies seem to sample various sites out of "saliva", "tongue", and "subgingival dental plaque" and closer review + update is needed.
- [major salivary gland](https://bugsigdb.org/Major_salivary_gland): these studies sample "saliva"
- [saliva-secreting gland](https://bugsigdb.org/Saliva-secreting_gland): this study samples "saliva"
- [buccal gland](https://bugsigdb.org/Buccal_gland): this study actually samples "buccal mucosa"

Note that we would only annotate the gland if indeed tissue from these glands (eg in case of a specific cancer in that gland) would have been taken, often enough those are just "saliva" samples

- [Mucosa](https://bugsigdb.org/Mucosa), these are two studies, one investigates "colonic mucosa" and one investigates "pharyngeal mucosa". Note "Mucosa" is all over the body and might thus represent very different body sites, so we always want to be as specific as possible for that.

Note further that a clean-up seems currently dependent on #148 being resolved first.

**Comment by lgeistlinger** [comment]
The body site should be updated to "Feces" for all experiments of these studies:

https://bugsigdb.org/Study_467
https://bugsigdb.org/Study_687

**Comment by claregri** [comment]
Hi, both of these studies have now been updated!

**Comment by lgeistlinger** [comment]
Great, thanks!

**Comment by lgeistlinger** [comment]
Hi @claregri @ftzohra22 - we have a solution in place for https://github.com/waldronlab/BugSigDB/issues/148, ie autocomplete for body site should work now. Can you be so good and proceed with the clean-up of studies associated with oral gland, major salivary gland, saliva-secreting gland, buccal gland, and mucosa, as outlined in my post above? Many thanks!

**Comment by lgeistlinger** [comment]
All body sites have been cleaned up accordingly
