### ISSUE TITLE
Video tutorials

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#152]
Tutorials: While I did find it relatively easy to navigate, it would benefit from having video tutorials on how to use the database, doing searches and downloads. And another video tutorial on how to upload a study would be very useful. 3-5 minute long YouTube videos would be really good with explanations of what all the fields mean and how to use the menu items.

**Comment by lgeistlinger** [comment]
Also adding @claregri to this one

**Comment by lgeistlinger** [comment]
Hi all - this came up as part of the review from Nature Biotech (which was very enthusiastic!).

I would think we make three tutorials:

1. High level navigation of the wiki (browsing studies / experiments / signatures, basic search + advanced search, requesting an account, reporting issues)  @lgeistlinger / @lwaldron 
2. Curation interface (adding a study and filling all fields) @ftzohra22 @claregri @rimsha1 
3. Data export + working with the data in R (zenodo, bugsigdbr) @lgeistlinger

**Comment by lgeistlinger** [comment]
@ftzohra22 @claregri @rimsha1 can we meet next week Mon / Tue to discuss this?

**Comment by rimsha1** [comment]
@lgeistlinger Hi Ludwig! I am seeing this a bit late, I was on vacation. My next available day is Thursday to meet, thanks! Rimsha

**Comment by lgeistlinger** [comment]
Now available on youtube: https://youtube.com/playlist?list=PLIUETfW6tVu2OGgZcIxqI7DbUBReHVdIq
