### ISSUE TITLE
New alpha diversity field: Faith's PD

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#153]
One reviewer raised the following point: For alpha diversity, there was no Faith’s PD even though it is a common alpha diversity metric. 

@tosfos: can we add a new alpha diversity field "Faith" that is

1. set to NA/blank for all studies in BugSigDB
2. the info for mouse-over should be: "Phylogenetic diversity, takes into account phylogenetic distance of all taxa identified in a sample"

**Comment by lwaldron** [comment]
👍 for this one, should do what the reviewer asks here.

**Comment by tosfos** [comment]
This was done. Please test.
![image](https://user-images.githubusercontent.com/10228795/208535086-71026e5d-bbd3-46e3-8dbc-5b2a39a68ce0.png)

**Comment by lgeistlinger** [comment]
Looks good, thanks!
