### ISSUE TITLE
New statistical analysis field: data transformation

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#154]
One reviewer raised the following point: There was no indication whether the datasets had been subject to clr-transformation or other compositional data analysis methods. It would be nice to have this as a field or a checkbox since these data are all compositional, but most studies do not adjust for this. I it would be nice to know which are.

After discussion with @lwaldron, we decided that this would be best addressed via a new statistical analysis field called "Data transformation". 

1. This field would be set to NA/blank for all studies already in BugSigDB,
2. This field would become a field for which we would like control possible values under https://bugsigdb.org/Help:Admin
3. A user should be able to select from the following options (@lwaldron can you check?):
- raw counts
- relative abundances
- centered log-ratio
- arcsine

**Comment by tosfos** [comment]
I assume this will go on the Study form and, therefore, will not vary between Experiments. Please confirm. Also, should this be placed at the end of the form/content page? Or somewhere else?

Please let me know once the final options have been confirmed.

**Comment by lgeistlinger** [comment]
This will indeed go in the experiment form in the "Statistical analysis" section. It should be the first field, ie before "Statistical test", "Significance threshold", etc.

**Comment by lwaldron** [comment]
👍 for where @lgeistlinger said.

**Comment by tosfos** [comment]
Will do. Should we include a tooltip? The other ones have it.

**Comment by lgeistlinger** [comment]
Yes: "Data transformation applied to microbial abundance measurements prior to differential abundance testing"

**Comment by tosfos** [comment]
We implemented this, assuming that you can only have one value in this field. Please let me know if that is incorrect:
![image](https://user-images.githubusercontent.com/10228795/208533674-21893199-1422-44ac-853f-51346ed99575.png)

**Comment by lgeistlinger** [comment]
Looks good, thanks!

**Comment by lwaldron** [comment]
One minor modification - it should be "arcsine square-root" or "arcsine sqrt" rather than just "arcsine"

**Comment by tosfos** [comment]
done

**Comment by cmirzayi** [comment]
Can we add an additional option for "log transformation"? This is different from a central log ratio.

Sorry if there's a way I can add these myself but I couldn't find it.

**Comment by lgeistlinger** [comment]
Added. Note that autocomplete values can be modified here: https://bugsigdb.org/Help:Admin
