### ISSUE TITLE
mouse-over info for citation section

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#155]
One reviewer raised the following point: for uploading new publications: the citation sections could use information links, especially for the URI. I think this stands for Universal Resource Identifier. Usually this is the URL, but it could be something else. And URI is very close to URL (looks the same) so it would be good to have one of those informational question marks next to the abbreviations. Just like you do with the Form Data (The Blue “i” button).

@tosfos: can we add the following info snippets for the citation section:

PMID: PubMed identifier for scientific articles
DOI: Digital object identifier for electronic documents
URI: Uniform resource identifier for web resources

**Comment by tosfos** [comment]
Sure

**Comment by lwaldron** [comment]
👍

**Comment by tosfos** [comment]
Should be all done on the content page and the form.

**Comment by lgeistlinger** [comment]
Small thing: could the info boxes themselves not contain the abbreviation in the beginning to be consistent with the info boxes for the other fields?

That means eg for PMID the info box currently reads "**PMID:** PubMed identifier for scientific articles" but should be "PubMed identifier for scientific articles". Same for DOI and URI.

**Comment by tosfos** [comment]
Done.

**Comment by lwaldron** [comment]
Looks good, I think this is closed.
