### ISSUE TITLE
Advanced Search for "feces" body site returns blank page

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#157]
I just noticed that [an Advanced Search for Body site: "feces"](https://bugsigdb.org/Special:RunQuery/Drill?Drill=Taxon%255Bis_list%255D%3D1%26Location%2Bof%2Bsubjects%255Bis_list%255D%3D1%26Location%2Blogic%3DAND%26Host%2Bspecies%255Bis_list%255D%3D1%26Body%2Bsite%255B0%255D%3Dfeces%26Body%2Bsite%255B1%255D%3Dsaliva%26Body%2Bsite%255Bis_list%255D%3D1%26Site%2Blogic%3DOR%26Condition%255Bis_list%255D%3D1%26Condition%2Blogic%3DAND%26NCBI%3D&_run=1&title=Special%3ARunQuery%2FDrill&pfRunQueryFormName=Drill&wpRunQuery=&pf_free_text=&Drill%5BTaxon%5D%5Bis_list%5D=1&Drill%5BLocation+of+subjects%5D%5Bis_list%5D=1&Drill%5BLocation+logic%5D=AND&Drill%5BHost+species%5D%5Bis_list%5D=1&Drill%5BBody+site%5D%5B%5D=feces&Drill%5BBody+site%5D%5Bis_list%5D=1&Drill%5BSite+logic%5D=OR&Drill%5BCondition%5D%5Bis_list%5D=1&Drill%5BCondition+logic%5D=AND&Drill%5BNCBI%5D=&wpRunQuery=&pf_free_text=) just returns a blank page with "Template:Drill". I assume that's because it would return too many results (since the same search for less-common body sites does return results) - that's OK, but would it be possible to provide some kind of helpful message like "Try a narrower search query to show results" ?

**Comment by tosfos** [comment]
We added a fix with ebe35e38e93d2bddc827d7d2611ddb632210f2cc. At some point this may happen again, but we can close this.
