### ISSUE TITLE
Change value of EFO in colorectal adenoma

### ISSUE THREAD

**Issue by seandavi** [waldronlab/BugSigDB#159]
Current: EFO:0000232
Suggested: EFO:0005406

**Comment by lgeistlinger** [comment]
Thanks @seandavi. Which version of BugSigDB are you using?

Currently:

"Colorectal adenoma" correctly points to EFO:0005406 on [BugSigDB's condition page](https://bugsigdb.org/Colorectal_adenoma) and also when linked on individual studies as eg on [Experiment 1 of Study 631](https://bugsigdb.org/Study_631). 

On the other hand, it it also exported as EFO:0005406 in the latest snapshot:

```
> dat <- bugsigdbr::importBugSigDB(version = "devel", cache = FALSE)
  |======================================================================| 100%

> spl <- split(dat[["EFO ID"]], dat[["Condition"]])
> spl[["colorectal adenoma"]]
 [1] "EFO:0005406" "EFO:0005406" "EFO:0005406" "EFO:0005406" "EFO:0005406"
 [6] "EFO:0005406" "EFO:0005406" "EFO:0005406" "EFO:0005406" "EFO:0005406"
[11] "EFO:0005406" "EFO:0005406" "EFO:0005406" "EFO:0005406" "EFO:0005406"
[16] "EFO:0005406" "EFO:0005406" "EFO:0005406" "EFO:0005406" "EFO:0005406"
[21] "EFO:0005406" "EFO:0005406" "EFO:0005406" "EFO:0005406"
```

**Comment by seandavi** [comment]
Sorry, @lgeistlinger. I meant the other way around. There is a curation value in Study 1 that has the name "adenoma" which actually refers to "colorectal adenoma." The literal meaning of EFO:0000232 is correct, but the paper is referring to EFO:0005406.

**Comment by lgeistlinger** [comment]
Got you. That's been updated on bugsigdb.org and should propagate into the export on Sunday.
