### ISSUE TITLE
Cascading protection (was: history for experiments and signatures?)

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#161]
Is there a way to view history for experiments and signatures? For example, clicking on History for https://bugsigdb.org/Study_249 takes you to https://bugsigdb.org/w/index.php?title=Study_249&action=history , which show edit history only for the study but not for the experiments and signatures contained within that study. Is there a way to show those histories on this history page as well?

And I am not sure if this is the same issue or a different issue, but if I add a study to my watchlist, it would be nice to get notifications also if any experiment or signature from that study is edited.

**Comment by tosfos** [comment]
> Is there a way to view history for experiments and signatures?

We can do that. We purposely hid most of this functionality for simplicity. Is there any other action (that exists for Studies)  we should consider adding?

**Comment by tosfos** [comment]
> I am not sure if this is the same issue or a different issue, but if I add a study to my watchlist, it would be nice to get notifications also if any experiment or signature from that study is edited.

It is a different issue. We should be able to implement something like this. Is this something that you want every time someone wants to watch a Study? Or should it work only if specifically chosen by the user?

**Comment by lwaldron** [comment]
OK I've opened a separate watchlist issue at https://github.com/waldronlab/BugSigDB/issues/164. 

> Is there any other action (that exists for Studies) we should consider adding?

I suppose that Protecting a study should also protect its experiments and signatures, but that seems like low priority.

**Comment by tosfos** [comment]
> I suppose that Protecting a study should also protect its experiments and signatures, but that seems like low priority.

That is already possible by clicking Protect for a Study and then clicking "Protect pages included in this page (cascading protection)". We can change that text, make it more prominent and/or make it checked by default.

Please let me know what would be the best option(s).

**Comment by tosfos** [comment]
The history tab was added.

![image](https://user-images.githubusercontent.com/10228795/223274837-3b851d77-7f64-4d80-a9fc-68650951a443.png)
![image](https://user-images.githubusercontent.com/10228795/223274913-f1b3c115-b25b-45c7-bd8b-896acaa74a8c.png)

**Comment by lwaldron** [comment]
The history tabs are great!

> > I suppose that Protecting a study should also protect its experiments and signatures, but that seems like low priority.
> 
> That is already possible by clicking Protect for a Study and then clicking "Protect pages included in this page (cascading protection)". We can change that text, make it more prominent and/or make it checked by default.
> 
> Please let me know what would be the best option(s).

I think the existing "cascading protection" is fine (and probably will be rarely used if ever), but it seems to be greyed out even after checking "Unlock further protect options":

![image](https://user-images.githubusercontent.com/639942/223361681-07f1a3f5-43f7-4e55-bb5d-c2008fe1ab7c.png)

**Comment by tosfos** [comment]
Strange. I confirmed that it is possible to click cascading protection even without unlocking the further protect options. But it does look greyed out in your screenshot. We'll see if we can reproduce this. Can you try again and see if you get any errors in your console?

**Comment by lwaldron** [comment]
Still greyed out for me. Is any of this from Chrome's devtools useful?

<img width="677" alt="image" src="https://user-images.githubusercontent.com/639942/224127075-0bf243f3-eec6-40fb-b02c-4eee7a42c774.png">

**Comment by lwaldron** [comment]
I was however able to add cascading protection to https://bugsigdb.org/Study_340 - if this is an occasional bug I can live with it for now as low-priority.
