### ISSUE TITLE
"Cancel" button not working for signatures

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#162]
When I enter edit mode for any signature, then press the "Cancel" button, nothing happens. I don't see the same issue for studies or experiments.

**Comment by cmirzayi** [comment]
It's also not working for me.

**Comment by tosfos** [comment]
It looks like this does actually work, but with certain exceptions. The built-in PageForms cancel button works similarly to a browser back button. So it won't work when opening the edit form in a new tab, or going directly to a Signature edit link like https://bugsigdb.org/Special:FormEdit/Signature/Study_508/Experiment_1/Signature_1?reload=1&returnto=Study_508

You'll see similar behavior for the other forms.

We can improve this functionality if needed, or maybe just remove the "Cancel" link.

**Comment by lwaldron** [comment]
In that case I'd say just removing the "Cancel" link is good enough, as users will know better what to expect when using the browser back button or closing the tab.

**Comment by tosfos** [comment]
Done. This can be closed.
