### ISSUE TITLE
Expanded study hamburger navigation menu cuts off article main text on high resolution displays 

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDB#163]
I am using a high resolution (4K) monitor and when I zoom the page to 125% (a comfortable size given the monitor resolution), the expanded hamburger menu begins to overlap the main article text (see screenshot below). Given the relative amount of blank horizontal space, perhaps the hamburger navigation menu can be skinnier.

![image](https://user-images.githubusercontent.com/13036789/222622545-f3d82f8e-7230-4117-9e59-9efe10aad5eb.png)

**Comment by tosfos** [comment]
We can make the menu narrower, but it would be less prominent then, and there likely will be some resolution where the menu will still cover some text.

It's intended that the navigation menu be used to navigate, and then be collapsed manually by clicking the hamburger icon again. 

@lwaldron do we want to change this or make it narrower?

**Comment by lwaldron** [comment]
If there's no ideal solution I can live with it as is. If at some point in the future there's a great new skin available that adapts better to all screen sizes then we can consider switching.
