### ISSUE TITLE
Watching a study should also include watching its experiments and signatures

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#164]
When I add a study to my watchlist, I should get notifications also if any experiment or signature from that study is edited or added. I think this can be the behavior always, I don't see a need to choose to watch only parts of the experiments/signatures under a study.

**Comment by lwaldron** [comment]
> Is this something that you want every time someone wants to watch a Study? Or should it work only if specifically chosen by the user?

I realize I didn't answer this specifically. I think it should happen every time someone wants to watch a Study, because there isn't much information in the Study alone (usually only PMID and study design entered).

**Comment by tosfos** [comment]
We're doing code review and testing right now, but this feature should be working. When you watch the Study, it should automatically also watch the Experiment and Signature pages.

**Comment by lwaldron** [comment]
I think this is working now?
