### ISSUE TITLE
"Duplicate experiment" not autofilling information correctly

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDB#166]
@tosfos When I click on duplicate experiment, the new page is autofilling information from the previous experiment and adding a “+” between words. e.g. condition, and group fields in the attachment below. 
![image](https://user-images.githubusercontent.com/45443641/223451457-9adc9c97-d38d-4d9c-b4d2-98695e6fd95b.png)

**Comment by lwaldron** [comment]
Just to clarify, the expected behavior is that there should not be any "+" between words in the new experiment. @ftzohra22 does the "+" still show after you save the new experiment?

**Comment by tosfos** [comment]
Should be better now. 

We did notice that duplicating values in certain fields will not copy over correctly. For example, https://bugsigdb.org/Study_608, in Experiment 1 contains an invalid Statistical test that includes a > sign. This sign does not copy over correctly. It probably won't happen very often, but we'll research if there's any way to improve it.

**Comment by tosfos** [comment]
Our research found that the issue with the > sign is not related to the duplication feature. It happens even with "regular" form editing, as you can see [here](https://bugsigdb.org/w/index.php?title=Study_608/Experiment_1&diff=next&oldid=77051). This is a bug in the underlying software that we will attempt to fix.

**Comment by tosfos** [comment]
This fix is going to be more of a long-term project. The main issue, which is common, is solved. But any duplication that includes a > sign will not be copied over correctly. Hopefully, that will be rare and can be fixed manually. I fixed Study 608. It looks like there are a few other places but it's probably not worth fixing if these are invalid values for the field anyway. See, for example, https://bugsigdb.org/Study_562.

**Comment by lwaldron** [comment]
I agree this is good enough.
