### ISSUE TITLE
How to edit allowed values for "Confounders controlled for"?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#167]
In https://bugsigdb.org/Study_144/Experiment_1 the "Confounders controlled for" contains "peak expiratory flow", which is [a valid EFO term](http://www.ebi.ac.uk/efo/EFO_0009718)) but is being flagged as invalid. There are also other pages containing values that are not EFO terms, but which nonetheless would be nice to allow, to clear the processing errors while requiring consistent use of that term.

Note, there is conflicting documentation about allowed terms:

* https://bugsigdb.org/Help:Admin links to  [here](https://bugsigdb.org/w/index.php?title=Property:Confounders_controlled_for/Values&action=edit) which looks like:
![image](https://user-images.githubusercontent.com/639942/223449797-7e6fac5b-3968-437c-acba-bd4b0cb7a394.png)

* And the warning tooltip links to https://bugsigdb.org/Property:Allows_value which links to https://bugsigdb.org/Property:Confounders_controlled_for, which is not an editable list (contains code `{{Set validation}}`)

**Comment by tosfos** [comment]
It looks like for "Confounders controlled for" (and "Matched on" as well), we are using the same allowed values as in the "Condition" field, which is the cause of the problem. Is it desired for these three fields to use the same list? If so, we'll need to figure out a workaround for this issue. Please advise.

**Comment by lwaldron** [comment]
"Confounders controlled for" "Matched on" could use the EFO ontology as well, but there are also arguments for treating these two differently than Condition and using instead a manual list for these:
1. they use a much more limited vocabulary than Condition
2. they more commonly have terms not from the EFO. Still not common, but Condition is (almost?) always found in EFO.

However, I can't think of any argument on the user side for "Confounders controlled for" and "Matched on" not using the same list as each other.

**Comment by tosfos** [comment]
Got it. I'll follow up about this.

**Comment by tosfos** [comment]
Please see the way we clarified this on the [Admin help](https://bugsigdb.org/Help:Admin) page. We're also going to improve the warning tooltip.

**Comment by tosfos** [comment]
This is all ready for review.

New tooltip:
![image](https://user-images.githubusercontent.com/10228795/227372240-e1bbbb66-7291-4039-9ad7-f4c02d5be269.png)

Clicking "Confounders controlled for" brings the user to the new version of the Property page:
![image](https://user-images.githubusercontent.com/10228795/227372404-71d241c5-95b5-4177-a480-b1392dccd98f.png)

Clicking "Edit list" brings up this interface, with some useful notices:
![image](https://user-images.githubusercontent.com/10228795/227372522-f0f409ab-edff-4dce-a012-ebea42704b9d.png)

**Comment by lwaldron** [comment]
This looks good!
