### ISSUE TITLE
Editing an experiment causes that experiment to disappear from the study when logged in as the user that edited that experiment

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDB#168]
I edited https://bugsigdb.org/Study_588/Experiment_1 changing the location of subjects. After saving the edit, I can no longer see Experiment 1 or the accompanying Signatures for Study 588 on the study page itself:
![image](https://user-images.githubusercontent.com/13036789/223832847-0e28a894-1cd4-461c-bbab-b5270d25620e.png)

Note I can still see that the experiment exists if I go to its url:
![image](https://user-images.githubusercontent.com/13036789/223833659-9fd24be7-1f88-4e26-9c51-b7a57322df3c.png)

Logging out of my account seems to resolve this issue and I can then see the experiment under the study again:
![image](https://user-images.githubusercontent.com/13036789/223833106-ee08d6c6-e8a7-4ffa-b6cd-1e41dc706092.png)

However if I log back into my account, the experiment is once again gone:
![image](https://user-images.githubusercontent.com/13036789/223833286-d067a95e-4bb0-46cd-afda-a4e85d811f95.png)

**Comment by cmirzayi** [comment]
Running the Refresh action from the ... menu on the study page resolves the issue. Perhaps Refresh should run automatically after editing an Experiment.
![image](https://user-images.githubusercontent.com/13036789/223834464-a41978d4-567d-40f1-b1e5-af1f1e13591b.png)

**Comment by tosfos** [comment]
We'll see if we can reproduce this. It might be difficult to resolve.

**Comment by tosfos** [comment]
We detected that these were two separate issues. One was related to cache purges happening too slowly, which was causing different views for logged-in/out users. That should be resolved now.

We did detect that there could be a separate issue when adding Experiments where the Study page is not being reliably refreshed. But it really shouldn't be happening based on the way BugSigDB is set up. I recommend holding things here, and reopening if it happens again. Hopefully, the cache improvements will solve it fully. If it does happen, please copy the HTML source of the page and send it to us.

**Comment by lwaldron** [comment]
Sounds good, we will re-open if the issue resurfaces.
