### ISSUE TITLE
Duplicating an experiment replaces spaces with "+"s in all fields

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDB#169]
As mentioned in title when you click the "Duplicate experiment" button the new experiment contains all the information of the previous experiment but all spaces are replaced with plus signs:
![image](https://user-images.githubusercontent.com/13036789/223846515-f8a76a52-f83b-4457-a71c-c23286ea547f.png)

**Comment by tosfos** [comment]
Closing as duplicate of #166
