### ISSUE TITLE
Signature entries not showing (study 667: https://bugsigdb.org/Study_667/Experiment_1/Signature_2)

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDB#172]
@lwaldron @tosfos For this study (https://bugsigdb.org/Study_667) none of the signature entries are populating. The curator confirmed they made changes and under their contribution there is an error(screenshot attached). Could we please prioritze resolving this. 
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/45443641/228932037-7d3c23c5-245d-45e8-b7cf-a6efa7472da6.png">

**Comment by tosfos** [comment]
We recently performed a performance related rewrite which caused this. Will fix.

**Comment by tosfos** [comment]
Should be ok now. It is possible that you may see this error again on very large pages. If you do, please reopen.

**Comment by ftzohra22** [comment]
Looks like it's happening on parts of the experiment section too. On https://bugsigdb.org/Study_750 the variable region isn't populating in any of the experiments except the first. Same on https://bugsigdb.org/Study_751
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/45443641/229238218-ece673b5-c8f4-4a9d-893f-8a961796a060.png">
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/45443641/229238442-4adadd56-7aac-4e1f-8d4f-052f07dcd161.png">

**Comment by lwaldron** [comment]
Probably related, seeing an unusual display of signatures at https://bugsigdb.org/Study_725 after I marked them reviewed:

<img width="974" alt="image" src="https://user-images.githubusercontent.com/639942/229299369-d744b9cf-d461-4ca9-bc15-5cb618ef86c9.png">

**Comment by lwaldron** [comment]
A couple more things I noticed on https://bugsigdb.org/Study_725 : 
- [ ] experiments and signatures that I marked as Reviewed still show "Needs Review" 
- [ ] I deleted Experiment 2 Signature 2, but the title is still there (this doesn't matter much, just a little odd).

**Comment by tosfos** [comment]
> Looks like it's happening on parts of the experiment section too. On https://bugsigdb.org/Study_750 the variable region isn't populating in any of the experiments except the first. Same on https://bugsigdb.org/Study_751

Tracking in #173

**Comment by tosfos** [comment]
> Probably related, seeing an unusual display of signatures at https://bugsigdb.org/Study_725 after I marked them reviewed:

Should be OK now:
![image](https://user-images.githubusercontent.com/10228795/230788587-553dde4f-bd37-4533-ac91-8514ffff90ad.png)

**Comment by tosfos** [comment]
>  I deleted Experiment 2 Signature 2, but the title is still there (this doesn't matter much, just a little odd).

Fixed. Should be OK moving forward as well.

![image](https://user-images.githubusercontent.com/10228795/230788633-8655e7d8-678e-4092-9c77-fd8d59814ee6.png)

**Comment by tosfos** [comment]
This can be closed
