### ISSUE TITLE
Study_727 not showing up in search results

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#174]
https://bugsigdb.org/Study_727 is titled "Tobacco exposure associated with oral microbiota oxygen utilization in the New York City Health and Nutrition Examination Study" but it doesn't show up on simple searches for any of these keywords (for example, https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=New+York+City&go=Go) or on https://bugsigdb.org/Tobacco_smoke_exposure_measurement. It seems this page isn't getting indexed, even though it was created 2+ weeks ago. FYI @sdgamboa @cmirzayi

**Comment by tosfos** [comment]
Looks like the ElasticSearch indexing stopped. We likely ran out of disk space, which is not so easy to fix. Will update.

**Comment by ftzohra22** [comment]
https://bugsigdb.org/Study_722 also not showing up on search results when searched by PMID: 31200089
<img width="1248" alt="image" src="https://github.com/waldronlab/BugSigDB/assets/45443641/3bcd759b-a2e8-4597-97f1-00880de94b09">

**Comment by tosfos** [comment]
We increased the disk space. Things should be all good here. [Test search](https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=31200089&go=Go):

![image](https://github.com/waldronlab/BugSigDB/assets/10228795/ea1d366d-cdd1-4d15-b4d3-4842953eb3ea)
