### ISSUE TITLE
Signatures have been created but are not getting added to Experiment 1 of Study_660

### ISSUE THREAD

**Issue by atrayees** [waldronlab/BugSigDB#175]
I have created pages for signatures 1 and 2 for Experiment 1 (https://bugsigdb.org/Study_660/Experiment_1/Signature_1 and https://bugsigdb.org/Study_660/Experiment_1/Signature_2), but they are not appearing on the Study (https://bugsigdb.org/Study_660).

**Comment by lwaldron** [comment]
Confirming that it appears that way for me too.

**Comment by tosfos** [comment]
I was able to get it to appear by directly visiting https://bugsigdb.org/Study_660/Experiment_1. That seems to have pushed the cache to update itself on the Study page too. We did just switch to a new solution for dependency updates, which may be the cause. Will check.

**Comment by tosfos** [comment]
We believe we have identified and fixed the issue. Please re-open if this happens again.
