### ISSUE TITLE
"State" always Incomplete in Signatures export

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#177]
When I download [signatures.csv](https://bugsigdb.org/Special:Ask/-5B-5BCategory:Signatures-5D-5D/-3FOriginal-20page-20name%3DSignature-20page-20name/-3FRelated-20experiment%3DExperiment/-3FRelated-20study%3DStudy/-3FSource-20data%3DSource/-3FCurated-20date/-3FCurator/-3FRevision-20editor/-3FDescription/-3FAbundance-20in-20Group-201/-3FNCBI-20export%3DMetaPhlAn-20taxon-20names/-3FNCBI-20export-20ids-20sc%3DNCBI-20Taxonomy-20IDs/-3FState/-3FReviewer/mainlabel%3D-2D/limit%3D5000/offset%3D0/format%3Dcsv/searchlabel%3DDownload-20all-20Signatures-20(CSV)/filename%3Dsignatures.csv), the "State" of every signature is "Incomplete". This is halting the https://github.com/waldronlab/BugSigDBExports/ GitHub Action.

<img width="900" alt="image" src="https://user-images.githubusercontent.com/639942/233183531-9af32192-2772-40dc-bf66-15cce62a1a80.png">

**Comment by lwaldron** [comment]
Also, the first column "Signature page name" of the signatures export is now blank as seen in the above screenshot, which also causes some problems in downstream analysis.

**Comment by tosfos** [comment]
Both issues should now be resolved.

**Comment by lwaldron** [comment]
Confirmed! One more related question, when do these export files get generated (like time of day?) so if it is scheduled we can time the BugSigDBExports action appropriately?

**Comment by tosfos** [comment]
They are generated on the fly, although some of the data may be cached for a bit.
