### ISSUE TITLE
Prevent entering PMIDs with leading zeros

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#178]
It is currently possible to enter a PMID with leading zeros. This should be prevented in the Study form where curators enter this information, as this leads to study duplication:

https://bugsigdb.org/Study_580 (PMID entered without leading 0)
https://bugsigdb.org/Study_731 (PMID entered with leading 0)

**Comment by lwaldron** [comment]
Amazing the corner cases we get once a lot of people start curating. Worth eliminating leading zeroes.

**Comment by tosfos** [comment]
Should be done now. Please let us know if you experience any issues.

**Comment by lgeistlinger** [comment]
Looks good! Thanks!
