### ISSUE TITLE
Edits made are not reflecting for Study_728

### ISSUE THREAD

**Issue by joy-commits** [waldronlab/BugSigDB#179]
I've been trying to work on this study: https://bugsigdb.org/Study_728
For the updates I'm making, it is not reflecting on the site.
I mean, I try to add signatures, and it doesn't show that it's been added. 
Also, I made some edits to the Experiments, but it doesn't show that an update has been made.

**Comment by tosfos** [comment]
Looks like #175 happening again. Sorry about that! I was able to get the Experiments and Signatures to display by visiting and/or purging the Experiments page. We'll check what needs to be done here.

**Comment by joy-commits** [comment]
Okay, thank you.

**Comment by tosfos** [comment]
We put the old dependency solution. Should be fixed moving forward.

**Comment by lgeistlinger** [comment]
@joy-commits can you confirm that this works now? Please close the issue if this resolves the problem. Thanks!
