### ISSUE TITLE
Study 722: Taxon "Bacteria" exported as empty string

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDB#180]
@tosfos https://bugsigdb.org/Study_722 is not displaying one of the bacteria names. To specify its the kingdom bacteria, the first name on the list under signature 1 and 2. Please see attached screenshot. 
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/45443641/236236613-d3ffee52-d4f1-4bbd-a6fb-d220de7b680a.png">

**Comment by tosfos** [comment]
This is a repeat of #160. Since this is the second time this happened, we'll investigate the cause further. Chances are the immediate issue will fix itself soon.

**Comment by tosfos** [comment]
The issue is on the NCBI API side. We created a workaround. It should be OK moving forward.

**Comment by lgeistlinger** [comment]
It seems there is a hiccup in the export here. The taxon "Bacteria" (NCBI ID: [2](https://www.ncbi.nlm.nih.gov/taxonomy/?term=2)) is exported as an empty string in both the `MetaPhlAn taxon names` as well as the `NCBI Taxonomy IDs` column. See the leading comma / semicolon in these columns (this is an excerpt from the exported `signatures.csv` file). 
 

<img width="1294" alt="Screen Shot 2023-05-20 at 1 02 28 PM" src="https://github.com/waldronlab/BugSigDB/assets/11871050/090b6d91-5eaf-4266-a129-0529cd6ebea4">


This causes some hiccups downstream as well. https://github.com/waldronlab/bugsigdbr/issues/43

**Comment by tosfos** [comment]
This should be resolved. It is possible that some of the old blank values have been cached and that was the cause. We can't purge the caches until we do a container restart, which we plan in a couple of weeks or so.

**Comment by lwaldron** [comment]
It's displaying correctly for me now. It's pretty odd that the authors reported "Bacteria" as both increased and decreased in cases and we were probably doing them a favor by not displaying that 😅
