### ISSUE TITLE
Visual improvements to quality control

### ISSUE THREAD

**Issue by tosfos** [waldronlab/BugSigDB#181]
Visual improvements to the quality control icons as a follow-up to https://github.com/waldronlab/BugSigDB/issues/156

**Comment by tosfos** [comment]
We reworked the icons and created a separate column. Please see what you think.

If it looks OK, we'll apply it to production.

![image](https://user-images.githubusercontent.com/10228795/236956597-e208563a-6dde-4fe0-81c2-a7031849966b.png)

**Comment by lgeistlinger** [comment]
Looks good to me. @lwaldron?

**Comment by tosfos** [comment]
Should we apply this to production?

**Comment by lwaldron** [comment]
Looks great, go ahead! @cmirzayi would you update the [documentation](https://bugsigdb.org/Help:Contents#Quality_control_flags_for_studies_and_for_taxa_.28.E2.9A.A0.E2.9C.95.EF.BF.BD.29)?

**Comment by tosfos** [comment]
This was applied to production.

**Comment by lwaldron** [comment]
Great! Will close this issue once the documentation is updated.

**Comment by cmirzayi** [comment]
Documentation has been updated. Additionally, I did my best to mimic the new icons via my primitive CSS skills. I also updated the potential contaminant alert picture used at https://bugsigdb.org/Help:Quality_control#Taxon-level_alerts to reflect the new symbols.
