### ISSUE TITLE
Saved Duplicated Experiments Error

### ISSUE THREAD

**Issue by jacquelynshevin** [waldronlab/BugSigDB#182]
When I save a Duplicated Experiment for Study 723, the only variables that display are the ones I populated myself. None of the auto-populated variables appear.

https://bugsigdb.org/Study_723
![STUDY723SNIP](https://github.com/waldronlab/BugSigDB/assets/133036084/654d29ac-876d-40e3-abc0-c610977d0194)

**Comment by tosfos** [comment]
That is by design. The page only shows values that have changed from the previous Experiment.

@lwaldron @lgeistlinger Should we add a note explaining this? If so, please reply with the text.

**Comment by lwaldron** [comment]
Sure, how about "Differences from previous experiment:" or "Differences from previous experiment shown", whichever is more appropriate for how it's displayed?

**Comment by tosfos** [comment]
We [added a note](https://bugsigdb.org/Study_723) for all experiments that are not "Experiment 1". Please review:
![image](https://github.com/waldronlab/BugSigDB/assets/10228795/86f82934-2fae-4181-9dde-d3cfcfd3e377)

**Comment by lgeistlinger** [comment]
Looks good!
