### ISSUE TITLE
Statistical Analysis Not Loading Variables

### ISSUE THREAD

**Issue by jacquelynshevin** [waldronlab/BugSigDB#183]
When I am filling out the experiment section, the statistical test LefSe and the Matched On age are not able to load or appear as an option.

![STUDY723SNIP2StatisticalAnalysis](https://github.com/waldronlab/BugSigDB/assets/133036084/dbf1c9c2-66bd-44d8-bc79-367bd5785002)

**Comment by lgeistlinger** [comment]
Seems to work again. Thanks!
