### ISSUE TITLE
Taxon name autocomplete not working

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDB#188]
When I type in a taxon ID, BugSigDB autocomplete works; however, it no longer works with taxon name like it used to. Some examples of it not suggesting anything for common taxa:

![image](https://github.com/waldronlab/BugSigDB/assets/13036789/d4a55c3c-9109-4196-943f-7a519a15449d)
![image](https://github.com/waldronlab/BugSigDB/assets/13036789/a66ac981-26ec-404a-b898-567d3dd4a933)
![image](https://github.com/waldronlab/BugSigDB/assets/13036789/e1dc50ee-64cc-4e8f-8435-3d6b0aa0edbf)

**Comment by tosfos** [comment]
We're checking this

**Comment by cmirzayi** [comment]
@tosfos Any updates on this? It is causing some hassles for our curators. Thanks!

**Comment by tosfos** [comment]
Sorry about the delay. We have a fix for it that is in our testing environment and it looks good. I expect it to be in production soon.

**Comment by tosfos** [comment]
This is fixed in production now. Apologies for the delay.
