### ISSUE TITLE
add more host species

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#193]
Add to the list [here](https://bugsigdb.org/w/index.php?title=Property:Host_species/Values&action=edit&editintro=Template:Editing_allowed_values) (currently only includes _Homo sapiens_, _Mus musculus_, and _Rattus norvegicus_ ). @lgeistlinger what's the best / easiest way to get a text list of potential plant and animal (including insects) host species?

**Comment by lgeistlinger** [comment]
It might be best to extend the list to the usual 10-20 model organisms and then add on demand. Or are you intending to add all 2.16 million known animals species (incl. 1.05 million known insect species) and all 380,000 known plant species here?

Another approach could be to take the animal and plant species from the KEGG complete genome list here which would provide for a somewhat more extensive list without going over board: https://www.genome.jp/kegg/catalog/org_list4.html

**Comment by lwaldron** [comment]
I like the 10-20 model organisms approach...

**Comment by lgeistlinger** [comment]
Ok I extend the field to include the following species:

Anolis carolinensis
Anopheles gambiae
Arabidopsis thaliana
Bos taurus
Caenorhabditis elegans
Canis familiaris
Danio rerio
Drosophila melanogaster
Equus caballus
Felis catus
Gallus gallus
Homo sapiens
Macaca mulatta
Monodelphis domestica
Mus musculus
Ornithorhynchus anatinus
Pan troglodytes
Rattus norvegicus
Sus scrofa
Xenopus laevis
Xenopus tropicalis

**Comment by lwaldron** [comment]
Thanks @lgeistlinger !
