### ISSUE TITLE
finding experiments with blank host species

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#194]
At least one study has been entered by leaving the host species blank: https://bugsigdb.org/Study_565, a study of dogs (see #193 - apparently the curator used this as a workaround for not finding _Canis lupis familiaris_ in the list). I think I am OK with keeping host species optional in case someone wants to enter something like pond microbiomes. But is there a Special page or search method that I could use to find blank host species?

**Comment by tosfos** [comment]
I believe we'll need to modify the template to support this. I'll follow up.

**Comment by lwaldron** [comment]
Yes, that sounds good. Ideally it would be great to be able to order the list, such as putting "Not specified" first or last and the rest alphabetized, but that's not critical. We've expanded the list of host species to ~20 model species.

**Comment by tosfos** [comment]
We put the "Not specified" first and added some processing to alphabetize the rest of the list. We also removed the invalid "contact us to have more species added" option, and instead, we added a note to the information popup. We can make that message more prominent if needed.
![image](https://github.com/waldronlab/BugSigDB/assets/10228795/d80cb52d-a34c-49ef-95f3-f79c4584aab1)

**Comment by tosfos** [comment]
The Drilldown display shows "Not specified" in the middle of the Host species list. Do you want us to move that to the beginning or end of the list?
![image](https://github.com/waldronlab/BugSigDB/assets/10228795/6f41d2ae-42d8-4618-9cbb-6e02e240ca24)

**Comment by tosfos** [comment]
[Here](https://bugsigdb.org/Special:RunQuery/Drilldown?Drilldown%5BLocation%20of%20subjects%5D=&Drilldown%5BHost%20species%5D=Not%20specified&Drilldown%5BBody%20site%5D=&Drilldown%5BCondition%5D=&Drilldown%5BTaxon%5D=&_run=1) is a direct link to see all the Studies with Experiments where the Host species is not specified.

Pasting the current list here for convenience:
1. [Fecal microbiome signatures of pancreatic cancer patients](https://bugsigdb.org/Study_424)
2. [Effects of amoxicillin treatment on the salivary microbiota in children with acute otitis media](https://bugsigdb.org/Study_503)
3. [Potential of fecal microbiota for early-stage detection of colorectal cancer](https://bugsigdb.org/Study_595)
4. [Differential Responses to Dietary Protein and Carbohydrate Ratio on Gut Microbiome in Obese vs. Lean Cats](https://bugsigdb.org/Study_772)

**Comment by lwaldron** [comment]
Great! I'd say "not specified" first in the drop-down list.

**Comment by tosfos** [comment]
I'm not sure what you mean. Can this task be closed? Or is there something else needed?

**Comment by lwaldron** [comment]
Yes, closing this issue. I meant the "not specified" option appearing at the top of the drop-down list, which it already is.
