### ISSUE TITLE
Experiments and Signatures temporarily not displaying after edit

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDB#196]
In https://bugsigdb.org/Study_798 only Study info section is visible.

**Comment by lwaldron** [comment]
From #197 : 
> In https://bugsigdb.org/Study_825 there are three experiments but the edits to the second and third aren't rendering. After clearing browser cache and even log-out and log-in, the issue still persists.

@SvetlanaUP can you specify what edits to experiments in https://bugsigdb.org/Study_825 aren't rendering, so we'll know if we're seeing the version with or without edits?

**Comment by lwaldron** [comment]
In https://bugsigdb.org/Study_798 I can see the experiments and signatures, but earlier this morning I also saw only the study. So there seem to be sub-pages temporarily disappearing after some action - @SvetlanaUP you said it was following marking something reviewed? Any details you can recall about actions you took preceding the experiments and signatures temporarily disappearing will be helpful. I also heard a similar report from a curator following editing.

**Comment by SvetlanaUP** [comment]
After clicking on "Mark reviewed" to approve curations of Experiment 1, Signature 1 and Signature 2 sections disappeared, one by one, after each click. HTH.

**Comment by SvetlanaUP** [comment]
As for bug in https://bugsigdb.org/Study_825, I am waiting for the outreachy applicant's answer to specify what edits were problematic.

**Comment by tosfos** [comment]
We haven't been able to reproduce this issue. Does anyone have a way that reliably reproduces the problem?

We believe this is a bug in one of the extensions we are using to help update the semantic dependencies. We can try to track it down, but it may be a significant project. We did try to switch to a different solution for the dependency updates, but it caused #175 and #179.

**Comment by SvetlanaUP** [comment]
@tosfos I just tried to reproduce it, without success. I'll let you know if it happens again and record it immediately.

**Comment by tosfos** [comment]
Closing as dup. Continuing in https://github.com/waldronlab/BugSigDB/issues/221
