### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#198]
Is there anything relatively straightforward we could do improve the search engine performance for searches for taxa or conditions (like https://www.mediawiki.org/wiki/Extension:WikiSEO ?) I'm starting to work on getting some links to the main page, but want to make sure there is something like a full site map including taxa and conditions that can be indexed by search engines.

**Comment by tosfos** [comment]
We installed WikiSEO a couple of years ago. We will improve the way it works. We also added a sitemap at that time. Was it submitted to Google? We will add it to the robots.txt so hopefully Google will see it either way.

**Comment by tosfos** [comment]
We updated the robots.txt, as you can see [here](https://bugsigdb.org/robots.txt). It would be good to check the [search console](https://search.google.com/search-console/about) to make sure that Google is happy with the site. Please let me know if you need help with that. We also improved some of the SEO meta tags. For example:
```
<meta property="og:title" content="The gut microbiota in conventional and serrated precursors of colorectal cancer - BugSigDB"/>
<meta property="og:site_name" content="BugSigDB"/>
<meta property="og:url" content="https://bugsigdb.org/Study_1"/>
<meta property="og:description" content="BACKGROUND: Colorectal cancer is a heterogeneous disease arising from at least two precursors-the conventional adenoma (CA) and the serrated polyp"/>
<meta property="og:image" content="https://bugsigdb.org/w/logo.png"/>
<meta property="article:tag" content="Adenoma,Cancer,Colorectal,Microbiome,Microbiota,Polyp,Serrated,Peters BA, Dominianni C, Shapiro JA, Church TR, Wu J, Miller G, Yuen E, Freiman H, Lustbader I, Salik J, Friedlander C, Hayes RB, Ahn J"/>
<meta property="article:modified_time" content="2022-05-20T16:52:21Z"/>
<meta property="article:published_time" content="2022-05-20T16:52:21Z"/>
```
As you can see, we're now setting a "title" which will equal the display title of the page. We're also putting the abstract in the "description" tag. And we're setting the "keywords" field to match the "keywords" :). Please confirm that we guessed all this correctly.

**Comment by tosfos** [comment]
Can this be closed?

**Comment by lwaldron** [comment]
Sorry for the delay, yes, thanks @tosfos
