### ISSUE TITLE
Formatting of Study 719

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#204]
Something's weird here with the formatting of the signature entries for https://bugsigdb.org/Study_719.
Do not observe this for other studies.

<img width="1207" alt="Screenshot 2023-11-08 at 6 54 59 PM" src="https://github.com/waldronlab/BugSigDB/assets/11871050/d9be9ef4-796d-4aa9-9424-79b1205ae5d4">

**Comment by tosfos** [comment]
The cause was that certain pages were created during the Lua conversion while the code was bugged. We fixed this and a few other pages.
