### ISSUE TITLE
PMID must be unique

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#205]
We have been observing several instances where curators didn't understand the "must be unique" message when trying to create a study that already exists in BugSigDB.

<img width="1011" alt="Screenshot 2023-11-13 at 2 34 37 PM" src="https://github.com/waldronlab/BugSigDB/assets/11871050/13aeaefb-c07e-41c6-9ffb-dd33f4e801ca">

In some of these instances curators went ahead and just created the study anyhow by leaving the PMID field blank and rather entered the DOI or URL and sometimes also added abstract etc manually, essentially leading to study duplication.

I wonder whether the error message "must be unique" could be even clearer and could be changed to "This study already exists in BugSigDB".

**Comment by tosfos** [comment]
We can customize that message but it would take a significant amount of effort. Would it be good enough to add some sort of message near the field that is always there and says something like "If you get the message "must be unique", this study already exists in BugSigDB and should not be added."?

If not, we can add some custom code.

**Comment by lwaldron** [comment]
The easy solution sounds fine to me @tosfos

**Comment by tosfos** [comment]
Sorry about the long delay. Does this work?
![image](https://github.com/waldronlab/BugSigDB/assets/10228795/a0a3cdf5-4842-4e2e-8caf-b4a48ea99e1d)

**Comment by lgeistlinger** [comment]
yes I think this is very clear.
