### ISSUE TITLE
New statistical test category doesn't show up

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#207]
Hi I added "MaAsLin2" as a new statistical test under https://bugsigdb.org/Help:Admin a couple of days ago. However, when I try to enter the test in the form it doesn't show up. In the beginning I thought this is a result of the caching, but as it is already a couple of days ago that I added it, I am not so sure anymore.

<img width="1030" alt="Screenshot 2023-11-17 at 4 58 16 PM" src="https://github.com/waldronlab/BugSigDB/assets/11871050/b34a330a-3c68-4b10-984f-b8a2184c89e8">

**Comment by tosfos** [comment]
We got the new value to show up in the form. We're still trying to determine why this happened, but this issue can be closed.

**Comment by lgeistlinger** [comment]
Thanks!

**Comment by tosfos** [comment]
Noting that we found the source of the issue and implemented a workaround.
