### ISSUE TITLE
Some trouble with Study 562 again

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#209]
Two issues with https://bugsigdb.org/Study_562:

1. The bottom of the page displays an error (see below)

<img width="1209" alt="Screenshot 2023-12-01 at 5 23 30 PM" src="https://github.com/waldronlab/BugSigDB/assets/11871050/73afc939-0273-441d-b353-2a99f520683d">

2. Maybe as a result of this error (?) the `signatures.csv` export from https://bugsigdb.org/Help:Export is malformatted in L626

<img width="1041" alt="Screenshot 2023-12-01 at 5 24 51 PM" src="https://github.com/waldronlab/BugSigDB/assets/11871050/e4e90aae-18fd-4207-bce6-c73f127c277b">

**Comment by lwaldron** [comment]
This is a real outlier study that we created to represent the "typical, healthy" microbiomes of various body sites, and it has a lot of large signatures. If accommodating it may compromise performance of the rest of the wiki, we could split it into multiple studies or something.

**Comment by lgeistlinger** [comment]
Looks like 1. has resolved on its own, and 2. was actually an artifact from inspecting the file in Excel. I don't see such a malformed line when opening the file in vim or reading into R line by line.

**Comment by jwokaty** [comment]
It sounds like this issue has been resolved and can be closed?

**Comment by lgeistlinger** [comment]
Yes this can be closed

**Comment by tosfos** [comment]
It probably depends on how loaded the server is when the page is requested. We'll check on how we can fix this.

**Comment by tosfos** [comment]
We're going to defer the loading of all the hierarchy information in the tooltip that is displayed on hover until the hover is actually performed. This should cut down on server load and fix timeout issues. The downside is that sometimes it may take a bit of time to load the information depending on the cache status. We think this is a worthwhile tradeoff. We'll experiment and let you know how it goes.

**Comment by cmirzayi** [comment]
Relatedly, experiment 10 on study 562 shows no signatures at all but I see an extremely long signature when I go to: https://bugsigdb.org/Study_562/Experiment_10/Signature_1

This is perhaps a bit more troubling because there isn't even an error message that something _should_ be there but isn't.

![image](https://github.com/waldronlab/BugSigDB/assets/13036789/a8b1a995-e44c-415a-9d31-20d66aa4fc8b)

**Comment by cmirzayi** [comment]
Just confirming that Study 562/Experiment 10/Signature 1 does not exist in the CSV exports or in any named version (devel, Zenodo) that I have checked.

**Comment by tosfos** [comment]
Closing as dup. Continuing in https://github.com/waldronlab/BugSigDB/issues/221
