### ISSUE TITLE
Simple search does not find study titles

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#219]
E.g., a search for: [Integrating microbial and host transcriptomics to characterize asthma-associated microbial communities](https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=Integrating+microbial+and+host+transcriptomics+to+characterize+asthma-associated+microbial+communities&go=Go)

returns:

> Create the page "[Integrating microbial and host transcriptomics to characterize asthma-associated microbial communities](https://bugsigdb.org/w/index.php?title=Integrating_microbial_and_host_transcriptomics_to_characterize_asthma-associated_microbial_communities&action=edit&redlink=1)" on this wiki! See also the search results found.
> 
> [Nasal cavity](https://bugsigdb.org/Nasal_cavity)
> olfactory apparatus. This includes the space bounded anteriorly by the nares and posteriorly by the choanae, when these structures are present. Read more Aliases
> 546 bytes (72 words) - 11:03, 2 July 2022
> [Asthma](https://bugsigdb.org/Asthma)
> EXAC Asthma unspecified Asthma unspecified (disorder) Asthma, Bronchial Asthma, unspecified Asthma, unspecified type, with acute exacerbation Asthma, unspecified
> 2 KB (228 words) - 16:13, 29 January 2022
> [Olfactory pit](https://bugsigdb.org/Olfactory_pit)
> which ends when the pits hollows out to form the nasopharynx[GO]. Read more Aliases Nasal pit Studies related to Olfactory pit Advanced search
> 239 bytes (30 words) - 12:00, 2 July 2022
> [Chronic Obstructive Asthma](https://bugsigdb.org/Chronic_Obstructive_Asthma)
> Chronic airway obstruction caused by asthma. Read more Studies related to Chronic Obstructive Asthma Advanced search
> 165 bytes (16 words) - 06:18, 3 November 2021

But a search for [26277095](https://bugsigdb.org/w/index.php?search=26277095&title=Special%3ASearch&profile=default&fulltext=1) correctly returns:

> Create the page "[26277095](https://bugsigdb.org/w/index.php?title=26277095&action=edit&redlink=1)" on this wiki! See also the page found with your search.
> 
> [Integrating microbial and host transcriptomics to characterize asthma-associated microbial communities](https://bugsigdb.org/Study_838)
> design case-control Citation PMID PubMed identifier for scientific articles. 26277095 DOI Digital object identifier for electronic documents. 10.1186/s12920-015-0121-1
> 79 bytes (1,092 words) - 23:52, 6 November 2023

**Comment by tosfos** [comment]
Fascinating! It looks like the ElasticSearch indexer ignores the display title. We'll check on it.

**Comment by tosfos** [comment]
Unless there's a rush for this, we're going to hold off on the fix until after your pending 1.39 upgrade so we don't need to code everything twice.

**Comment by tosfos** [comment]
We have a fix ready for this issue. We'll deploy it to production shortly. You may notice some incomplete search results for a few hours while a reindex is in progress.

**Comment by tosfos** [comment]
This will be deployed this week. The search reindex may take up to 5 hours.

**Comment by tosfos** [comment]
This is now complete. The original search now works better:  [Integrating microbial and host transcriptomics to characterize asthma-associated microbial communities](https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=Integrating+microbial+and+host+transcriptomics+to+characterize+asthma-associated+microbial+communities&go=Go)
