### ISSUE TITLE
Account Request Failure

### ISSUE THREAD

**Issue by Millicent-adzepa** [waldronlab/BugSigDB#222]
Good evening,
Please I need help with my account request.
I requested an account to start my second task. After filling out the forms, I waited for 2 hours without a confirmation link in my email, so I figured that I might have missed a letter in my email, then decided to request a new one, and i got the confirmation within a few minutes. I clicked on the link, and it was successful.
I tried logging in and could not, so I requested a password reset. then the attached email was sent.  Please, how do I go about it? It has been 3 days since it happened.
![WhatsApp Image 2024-03-09 at 9 26 33 PM](https://github.com/waldronlab/BugSigDB/assets/137197138/cfd9a4b4-c196-4f73-bee0-dc3f89bb474f)

 Counting on your usual cooperation. 
thank you

**Comment by cmirzayi** [comment]
Hi Milly,

Please make your request on Slack. This is for reporting bugs with the BugSigDB platform.
