### ISSUE TITLE
Lua error: too many expensive function calls

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#224]
See https://bugsigdb.org/Study_971 - e.g. Experiment 12. I note that the error doesn't occur when navigating directly to https://bugsigdb.org/Study_971/Experiment_12. Note - this is an extremely large number of experiments for a study, and  and might not be worth supporting so many experiments if it would reduce performance on the rest of the site. 

<img width="1186" alt="image" src="https://github.com/waldronlab/BugSigDB/assets/639942/f05f7719-52a3-4ce3-8930-666185ea067e">

**Comment by AleruDivine** [comment]
Hello! 👋

**Comment by AleruDivine** [comment]
Hello! 👋

I would like to report this error message in my study page. 

“Lua error: too many expensive function calls”

Signatures 1 and 2 in experiment 126
Signature 1 in experiment 127

Thank you so much! 

Link to study: https://bugsigdb.org/Study_1048

<img width="1440" alt="Screenshot 2024-03-28 at 12 21 13" src="https://github.com/waldronlab/BugSigDB/assets/111589884/f1b06d11-1c67-4c02-8627-6dff6fbd94eb">

<img width="1440" alt="Screenshot 2024-03-28 at 12 21 21" src="https://github.com/waldronlab/BugSigDB/assets/111589884/ee005e8e-5060-4501-880f-3e87fc9c3e45">

**Comment by tosfos** [comment]
We doubled the limits and it helped for both of these pages. Note that at a certain size the limits will still kick in and that's by design.

**Comment by AleruDivine** [comment]
Thanks! There's no more error messages🥳🥳

**Comment by lwaldron** [comment]
Should be quite enough, if we ever hit the new limits we can abbreviate what we take from the paper 😅

**Comment by bolanlew** [comment]
Hi
I would like to report this error message in my study page.

“Lua error: too many expensive function calls”

Signatures 1 and 2 in experiment 109-159

Thank you so much!

**Comment by lwaldron** [comment]
@bolanlew which study are you referring to? @AleruDivine I am no longer seeing any errors on https://bugsigdb.org/Study_888. But a study with 35 experiments is a pretty extreme outlier, and perhaps it is OK to leave an error here if fixing it has any performance cost for other studies.

**Comment by AleruDivine** [comment]
Hi @lwaldron, that’s right! I don’t see the error messages anymore🫨 I don’t have any proof because I didn’t take a screenshot but they were really there this morning. I am glad they aren’t there anymore.
I’ll proceed with completing the curation as I am nearly finished. Hopefully they don’t come up anymore.🤞

**Comment by bolanlew** [comment]
would like to report this error message in my study page.

https://bugsigdb.org/Study_1048
@lwaldron
“The time allocated for running scripts has expired ”

Signatures 1 and 2 in experiment 109-159

Thank you so much!
