### ISSUE TITLE
Prune duplicated taxa in a signature

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#26]
It is possible to enter the same taxon multiple times in a signature. These could be pruned in the database, e.g. using a `unique` operation. It's mostly aesthetic and won't affect analyses, and probably won't happen much anyways, so it's not a big deal.

**Comment by tosfos** [comment]
This is some strange behavior. It looks like if you try to add an already-existing token, PageForms will assume that you are trying to remove that token (similar to clicking the x). Should we research this?

**Comment by lgeistlinger** [comment]
@lwaldron what do you think? An up-to-date example would be trying out to add the already contained "Firmicutes" to https://bugsigdb.org/Special:FormEdit/Signature/Study_267/Experiment_9/Signature_2 which will result in the [behavior described above](https://github.com/waldronlab/BugSigDB/issues/26#issuecomment-736718974). I'd be ok with leaving things as is.

I don't think it is too problematicwould just close?

**Comment by lwaldron** [comment]
So the problem only happens when you create a signature, save it, then edit it again and try to add an existing taxon again? It would be worth investigating someday but it's an unusual enough situation I would put it at the bottom of priorities for now. Good catch though, @lgeistlinger.

**Comment by tosfos** [comment]
Not quite. You can see it by editing any signature page. Try to add a taxon in the NCBI field, then immediately try to add the same taxon again. Instead of adding the taxon a second time, or ignoring the attempt, the form will instead remove the taxon completely.

**Comment by lwaldron** [comment]
OK that's pretty weird, and seems worth bumping up to medium priority.

**Comment by tosfos** [comment]
This should be fixed. We resolved it by not allowing the selection of a taxon that has already been added. Please test.

**Comment by lgeistlinger** [comment]
Tested + works great. Many thanks @tosfos !
