### ISSUE TITLE
Reproducible installation of bugsigdb.org

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#33]
Want a containerized installation or instructions for otherwise easily reproducible installation of the full bugsigdb.org.

**Comment by tosfos** [comment]
Should this go in a new repo? I don't have the permissions to create one.

**Comment by lwaldron** [comment]
Sorry I just saw this. For the bugsigdb.org codebase, I'd say just use this repo. For something like the NCBI module, I would create a new repo (or give you administrative permissions to do it), although you could also host that on a wikiworks github if you prefer.

**Comment by tosfos** [comment]
Code base done. https://github.com/waldronlab/BugSigDB/commit/2b7873edef884677fa575472f2325d03eb4e11fc

**Comment by tosfos** [comment]
For NCBITaxonomyLookup, I'd recommend that we request a repo on the WikiMedia Foundation's servers and then document it at mediawiki.org. What do you think?

**Comment by lwaldron** [comment]
Yes, I like that idea.--

Levi Waldron

Associate Professor

Department of Epidemiology and Biostatistics

CUNY Graduate School of Public Health and Health Policy

Institute for Implementation Science in Population Health

55 W 125th St, New York NY 10035

https://waldronlab.io

**Comment by tosfos** [comment]
I believe this can be closed.
