### ISSUE TITLE
Customized search features

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#49]
The current [search page](https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=&go=Go) with its default, Multimedia, Everything, and Advanced options are hard to understand how to use for this wiki. It would be very helpful to have a search page with fields customized to the wiki. 

For something to consider, we have several hierarchical ontologies: taxonomy, Body site (Uberon Ontology), Condition (Experimental Factor Ontology), so it may be possible to implement hierarchical searches for all those. Body site and Condition would also make nice filters for the "fake taxon" pages.

**Comment by tosfos** [comment]
Checking on status please. I believe certain new requests are related to this, such as #62 #57 #56

**Comment by lwaldron** [comment]
Thanks @tosfos. I have a hard time picturing what those will look like, which makes me inclined to say both, at least in basic form until we have a chance to user-test them then decide and refine. The drilldown-type page sounds like what is described in #56, so perhaps start with that. 

If we wanted to allow users to narrow down the signatures shown on a taxon page, would that be using a custom form?

**Comment by tosfos** [comment]
> The drilldown-type page sounds like what is described in #56, so perhaps start with that.
We'll think about the use case here and research our options. In all likelihood, one of these will be sufficient.

> If we wanted to allow users to narrow down the signatures shown on a taxon page, would that be using a custom form?
How would they be narrowed down? Also, there aren't really that many signatures on one Study page, are there?

**Comment by lwaldron** [comment]
> We'll think about the use case here and research our options. In all likelihood, one of these will be sufficient.

Sounds good.

> > If we wanted to allow users to narrow down the signatures shown on a taxon page, would that be using a custom form?
> 
> How would they be narrowed down? Also, there aren't really that many signatures on one Study page, are there?

I was mainly thinking about researchers with an interest in a particular body site or system (based on Uberon Ontology) or condition (based on Experimental Factor Ontology). Those would probably be the main filtering criteria for other searches as well. I meant filtering from a taxon page, not a study page, but the same behavior could instead be a part of a search page that allows search based on taxonomy, body site/system, and condition.

**Comment by tosfos** [comment]
> I meant filtering from a taxon page, not a study page
Right. Sorry about that!

Actually the Taxon page is already a query page in disguise, so adding some form fields for filtering would be very easy. Let's try it there as I think you'll be happy with the results.

**Comment by tosfos** [comment]
We added a rough draft of these 2 filters on the Taxon page.
![image](https://user-images.githubusercontent.com/10228795/108918452-6665f400-75ff-11eb-8a28-92dc3c5d447c.png)
Please check here: https://bugsigdb.org/Special:RunQuery/Taxon?Taxon[NCBI]=201174&_run=1

**Comment by lwaldron** [comment]
I like the filter. A couple great enhancements, if they are feasible, would be to:
1. in the dropdown, show only items with non-zero results. 
2. show parent terms from the Uberon and EFO ontology (e.g. allowing filtering for all types of cancer, or all gastrointestinal sites)

**Comment by tosfos** [comment]
> show parent terms from the Uberon and EFO ontology (e.g. allowing filtering for all types of cancer, or all gastrointestinal sites)

Can you please explain this some more? Are you looking for multiple-level filtering? Is there a list with the hierarchy?

**Comment by tosfos** [comment]
> in the dropdown, show only items with non-zero results.

This won't be simple. We estimate 2 hours to experiment and see how it goes. Please let me know.

**Comment by lwaldron** [comment]
I'd say this isn't the highest priority then. Some grouping of ontology terms under a higher level of hierarchy (ie all diseases under "cancer") seems better to prioritize. Or even higher priority, main search/browse features for the front page, including replacement for the default MediaWiki search box.

**Comment by lwaldron** [comment]
Maybe we need to touch base again to decide on search functionality. Search and browse functionality, incorporated into a more functional home page, now seem like the highest-priority items.

**Comment by lwaldron** [comment]
(moved from https://github.com/waldronlab/BugSigDB/issues/73): In the drill-down, it is a bit frustrating only being able to choose one location of subjects, one body site, one condition, etc. For example, there are the following closely related conditions: gastric adenocarcinoma, gastric cancer, and gastric carcinoma, but I can't combine them all into a drill-down search. Similarly I can't drill down to include all the North American locations. If it is feasible to allow selecting more "or" filters from the same category, it would be useful.

We could also think about how to use the ontologies that body site and condition are based on, but this would turn drill-down into something more like we do for Taxa, where drilldown results also show descendents of the Taxon. That said, the drill-down feature is already quite functional and interesting, and these would be enhancements rather than requirements for basic functionality.

**Comment by tosfos** [comment]
We set up a rough draft for this feature. You can see the form [here](https://bugsigdb.org/Special:RunQuery/Drill?Drill%5BCondition%20logic%5D=AND&Drill%5BLocation%20logic%5D=AND&Drill%5BSite%20logic%5D=AND&_run=1) (click "Set up form"). And you can see sample results for the above conditions, [here](https://bugsigdb.org/Special:RunQuery/Drill?Drill=Condition%2Blogic%3DAND%26Location%2Blogic%3DAND%26Site%2Blogic%3DAND&_run=1&title=Special%3ARunQuery%2FDrill&pfRunQueryFormName=Drill&Drill%5BTaxon%5D%5Bis_list%5D=1&Drill%5BLocation+of+subjects%5D%5Bis_list%5D=1&Drill%5BLocation+logic%5D=AND&Drill%5BHost+species%5D%5Bis_list%5D=1&Drill%5BBody+site%5D%5Bis_list%5D=1&Drill%5BSite+logic%5D=AND&Drill%5BCondition%5D%5B%5D=gastric+adenocarcinoma&Drill%5BCondition%5D%5B%5D=gastric+cancer&Drill%5BCondition%5D%5B%5D=gastric+carcinoma&Drill%5BCondition%5D%5Bis_list%5D=1&Drill%5BCondition+logic%5D=OR&Drill%5BNCBI%5D=&wpRunQuery=Run+query&pf_free_text=).

The system needs some more work, but I wanted to get some feedback before we continue.

This is a completely different type of system from the drilldown we have right now. Would this be a good solution to work in tandem with the drilldown? Or should it replace the drilldown completely?

Please let me know what you think.

**Comment by lwaldron** [comment]
Did my first trying it out and it looks amazing. At first I didn't understand why the search results seemed to include search terms I hadn't entered, then I realized it was showing characteristics of the experiments found in the results. Might be good to show an "About these search results" link for those who don't get it right away. More thoughts @lgeistlinger @ftzohra22 @rimsha1 @cmirzayi @jwokaty ?

**Comment by tosfos** [comment]
We added a help hint section (which is hidden until clicked) directly onto the form:
![image](https://user-images.githubusercontent.com/10228795/139715819-282a96bb-8f83-4019-86ce-02886e640294.png)

It also links to an [extended help page](https://bugsigdb.org/Help:Wildcard_Semantic_Search).

We also changed the page heading.

**Comment by lwaldron** [comment]
Yes.
