### ISSUE TITLE
"16s" capitalization in "variable region"

### ISSUE THREAD

**Issue by chuttenh** [waldronlab/BugSigDB#59]
This one's minor :)

**Comment by tosfos** [comment]
This is marked low priority, but the mixed capitalization is causing some confusion for us. We're going to go ahead and fix this as it should be quick.

**Comment by tosfos** [comment]
This is now done, as you can see [here](https://bugsigdb.org/Study_238/Experiment_3). Please review.

**Comment by lgeistlinger** [comment]
Looking good!
