### ISSUE TITLE
Taxon pages (was: Microbial annotations)

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#6]
How do we begin annotating the microbial taxonomy with morphological and physiological properties? For example:
* [obligate aerobes](https://en.wikipedia.org/wiki/Obligate_aerobe)
* [facultative anaerobes](https://en.wikipedia.org/wiki/Facultative_anaerobic_organism)
* [obligate anaerobes](https://en.wikipedia.org/wiki/Obligate_anaerobe)

We would want to be able annotate individual taxa or hierarchical clades of the taxonomy.  This is the high-priority item

Eventually we would want to be able to export and analyze these like signatures, at any level of the taxonomy. This is lower-priority.

**Comment by tosfos** [comment]
At some point, we'd like to try and rework all the queries on this page (using Lua), but it doesn't have to be done now if performance is acceptable.

Can this be closed?

**Comment by lgeistlinger** [comment]
@lwaldron: input required.

**Comment by lwaldron** [comment]
Yes let's close for now. A rework for performance would be great to do in the near-ish future but deserves a new issue.
