### ISSUE TITLE
Link all structured annotations to each other

### ISSUE THREAD

**Issue by chuttenh** [waldronlab/BugSigDB#60]
That is, for each annotation value, make it a clickable link that lists all features of the same type with the same annotation (e.g. experiments with the same type, condition, studies from the same group, etc.)

**Comment by lgeistlinger** [comment]
Just screening through some of the older issues that we haven't attended to yet. This sounds useful, is this something that we could implement (@tosfos) and that we would want implement (@lwaldron)? 

For condition and body site this is already in place via the glossary, ie when clicking on a certain condition / body site you are referred to a page that links all studies related to that condition / body site.

Other attributes that would be of interest IMO would be:

study design
location
sequencing type
statistical test

**Comment by tosfos** [comment]
We can do this. It's fairly simple.

**Comment by lgeistlinger** [comment]
@lwaldron let us know whether we can go ahead with this.

**Comment by lwaldron** [comment]
Absolutely

**Comment by tosfos** [comment]
Please review on a page like [this](https://bugsigdb.org/Study_2). We implemented this in 2 different ways to see which way you prefer. Please check how we implemented it for "study design" and "Statistical test". 

I think (option 1) the "study design" method is more technical and less user-friendly. The (option 2) "statistical test" method looks nicer and allows users to quickly pick Experiments with other tests. The implementation is more complex but probably worth it.

We can improve on either method. For example, in option 2, I assume you'll want us to link to the Study page.

**Comment by lwaldron** [comment]
Sorry I missed this too - I agree with you on option 2, it looks great. Linking to the study page rather than to many experiments within also sounds more user-friendly, although it seems like a minor point.

**Comment by lgeistlinger** [comment]
Just checking back what's the status of this?

**Comment by tosfos** [comment]
Should be all done.

**Comment by lwaldron** [comment]
This looks great - really nice being able to click around the wiki like this, and loading is fast.
