### ISSUE TITLE
Search results format is pretty unintuitive

### ISSUE THREAD

**Issue by chuttenh** [waldronlab/BugSigDB#62]
Clearly still reliant on the default MediaWiki format.
Could be made more structured, e.g. focusing on tag types / annotations
Or less structured, e.g. simple list like Google

**Comment by lwaldron** [comment]
This is being addressed under issue https://github.com/waldronlab/BugSigDB/issues/49 - see screenshot of draft drill-down search for a taxon, and Phylum Actinobacteria example at https://bugsigdb.org/Special:RunQuery/Taxon?Taxon%5BNCBI%5D=201174&_run=1.
