### ISSUE TITLE
multiple valid "matched on" values produce invalid warning

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#65]
See for example https://bugsigdb.org/Study_425#: Experiment 1 "matched on" contains two valid entries: `age` and `sex`, but it shows the orange `!` sign.  The warning sign goes away if only age or only sex is entered. No warning sign should be shown if all entries are valid. Not sure if this is affecting other fields as well. This is a minor issue.

**Comment by tosfos** [comment]
Should be all good now. Please review and close.

**Comment by lgeistlinger** [comment]
@ftzohra22 can you check and close the issue if things are looking ok for you?

**Comment by ftzohra22** [comment]
looks good. Thank you!
