### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#66]
Front page works loads, but some others do not - for example just now I got this error for  https://bugsigdb.org/Study_1 and https://bugsigdb.org/Study_4, but not for studies 2 or 3. Issue was first reported to me yesterday by three different curators starting ~8pm. 

```
504 Gateway Time-out
nginx/1.14.0 (Ubuntu)
```

**Comment by lwaldron** [comment]
The performance of taxon pages is also very slow, and I got a 504 Gateway Time-out also for [Neisseria](https://bugsigdb.org/Special:RunQuery/Taxon?Taxon%5BNCBI%5D=482&Taxon%5BBody%20site%5D=&Taxon%5BCondition%5D=&_run=1).

**Comment by lgeistlinger** [comment]
Maybe related to that I have trouble to export the signatures.csv from bugsigdb.org (see attached screenshot)

![Screen Shot 2021-02-25 at 10 55 34 AM](https://user-images.githubusercontent.com/11871050/109179885-57df2000-7758-11eb-8616-d07120beb9ad.png)
.
Exporting the experiments.csv and studies.csv is not affected, and works fine.

**Comment by lgeistlinger** [comment]
Trying to read the exported signatures.csv file from within R fails as well:

``` 
> sigs <- readr::read_csv("https://tinyurl.com/yakgsowm")
Error in (function (con, what, n = 1L, size = NA_integer_, signed = TRUE,  : 
  transfer closed with outstanding read data remaining
```

**Comment by tosfos** [comment]
Yes, it looks like this could all be related. It seems the server ran out of disk space. We freed up some space and things should work now.

**Comment by lgeistlinger** [comment]
Thanks! Can confirm that I am able to pull the export csv files again.

**Comment by ftzohra22** [comment]
@lgeistlinger and @tosfos not getting the error any more. There was a momentary issue when 'add a new signature' was clicked but that seems to be working now as well =)

**Comment by lgeistlinger** [comment]
thanks @ftzohra22 !
