### ISSUE TITLE
Condition property of Category Experiments is empty on Semantic Search

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDB#67]
Experiments (category) have a property called Condition (not to be confused with the Condition field of Semantic Search). When you try a Semantic Search to pull data from Experiments, you only get a single Condition and the rest of the rows are blank. Here's a Semantic Search where this happens:

```
{{#ask: [[Category:Experiments]]
 |?Condition
 |format=broadtable
 |limit=5000
 |offset=0
 |link=all
 |sort=Page sort number
 |order=asc
 |headers=show
 |mainlabel=-
 |searchlabel=... further results
 |class=sortable wikitable smwtable
}}
```

Compare to another property of Experiments which does display correctly:

```
{{#ask: [[Category:Experiments]]
 |?Group 0 name
 |format=broadtable
 |limit=5000
 |offset=0
 |link=all
 |sort=Page sort number
 |order=asc
 |headers=show
 |mainlabel=-
 |searchlabel=... further results
 |class=sortable wikitable smwtable
}}
```

**Comment by lwaldron** [comment]
These are also missing in bulk experiments export (https://tinyurl.com/yb2fmpa3). I noticed they now show as red hyperlinks on study pages (https://bugsigdb.org/Study_4).

**Comment by tosfos** [comment]
Should be OK now. Please test and close. [Here](https://bugsigdb.org/User:WikiWorks/Condition_issue) is a link to the above queries showing that the issue is fixed. Some of the Condition fields have processing errors, but other than that, the field should work fine now.

This issue was caused by an erroneous edit we did to support #55.

**Comment by lgeistlinger** [comment]
Hi @cmirzayi can you confirm that the issue is resolved and close if that's the case. Thanks!

**Comment by cmirzayi** [comment]
Can confirm it's fixed.
