### ISSUE TITLE
How should we clear studies under Stale reviews?

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDB#68]

**Comment by lgeistlinger** [comment]
Hi @ftzohra22 we would need some more context here and being pointed to 1,2 example cases in order to be able to comment on the issue. Thanks!

**Comment by lwaldron** [comment]
I see the list at: https://bugsigdb.org/Help:Needs_review

If I click on the first one (https://bugsigdb.org/Study_1/Experiment_1/Signature_1), it shows as already reviewed, and doesn't have the option like an unreviewed study to "mark reviewed". So I'm not sure either how to mark this as "reviewed" again and no longer "stale".

**Comment by ftzohra22** [comment]
my apologies. I meant under the section Stale reviews here (https://bugsigdb.org/Help:Needs_review) we have papers that were already reviewed (on the sheet) but some changes made on them after importing to the wiki.

**Comment by tosfos** [comment]
You go to the study and click "Flag for review". I did that on this page: https://bugsigdb.org/Study_1/Experiment_1/Signature_1

Once that is done, it can be reviewed again.

**Comment by lgeistlinger** [comment]
Hi @ftzohra22 please check whether this answers your question and close the issue if that is the case. You can also further comment if you have additional questions regarding this issue. Thanks!

**Comment by ftzohra22** [comment]
Thank you @tosfos that was helpful!
