### ISSUE TITLE
Signature page error

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDB#72]
@tosfos @lgeistlinger @lwaldron It seems like the signature page is not working. I was able to add an experiment but getting this error message when I try to edit or add a signature. 
https://bugsigdb.org/Special:FormEdit/Signature?Signature%5BBase%20page%5D=Study%20428%2FExperiment%201&reload=1&returnto=Study_428%2FExperiment_1

**Comment by lwaldron** [comment]
@ftzohra22 would you post a screenshot also just in case it's intermittent?

**Comment by ftzohra22** [comment]
Sure. Here's a screenshot of the error 

![image](https://user-images.githubusercontent.com/45443641/119718095-28ae7c80-be35-11eb-9731-65078e711b7b.png)

**Comment by tosfos** [comment]
Should be all good now. Please review and close.

**Comment by ftzohra22** [comment]
Yes perfect. Thank you!
