### ISSUE TITLE
Improve text search

### ISSUE THREAD

**Issue by tosfos** [waldronlab/BugSigDB#75]
Install ElasticSearch

**Comment by tosfos** [comment]
The full-text search has been improved. You can see an example of the improved search behavior [here](https://bugsigdb.org/w/index.php?search=microbiota&title=Special%3ASearch&profile=default&fulltext=1).

Please let me know if additional improvements are needed.

**Comment by tosfos** [comment]
Please note that searching for a taxon won't return the taxon query page, since it is not a real page. See [this](https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=Granulicatella%E2%80%AF&go=Go) example.

**Comment by lwaldron** [comment]
The search works really nicely. I like that it returns results from studies, experiments, and signatures. It doesn't seem like a disadvantage not to return the taxon page, you can click on that from the signature if you want to see the taxon page.

The only thing I might change would be the search options to make them more relevant to this wiki. Maybe I just need to be educated as to what the "Search in namespaces" options, but we don't have any multimedia. grouping signatures and experiments from the same study would be nice if practical but not key.

**Comment by tosfos** [comment]
> Maybe I just need to be educated as to what the "Search in namespaces" options, but we don't have any multimedia.

Multimedia would include any uploads. If you don't plan on uploading documents, we can remove that option. Please let me know.

For a simple example about namespaces, the "Content pages" option would only include pages that contain content like Studies, Experiments or Signatures. It wouldn't include pages in the Help namespace. So by default [if you search for "Autocomplete"](https://bugsigdb.org/w/index.php?title=Special:Search&profile=default&search=autocomplete&fulltext=1) you'll get no results. [If you click on the "Everything" option](https://bugsigdb.org/w/index.php?title=Special:Search&profile=all&search=autocomplete&fulltext=1) it will search the Help namespace as well and you will get a result.

We can hide that section of the Search results page if you'd like, and we can change the default behavior to search everything if that would be better.

> grouping signatures and experiments from the same study would be nice if practical but not key.

This is definitely not easy. Please let me know if we should research our options.

**Comment by lwaldron** [comment]
> > grouping signatures and experiments from the same study would be nice if practical but not key.
> This is definitely not easy. Please let me know if we should research our options.

No no, not worth that much effort. What about somehow displaying more prominently whether the result is a Study, Experiment, or Signature? Although this isn't really necessary either since the words "Experiment" and "Signature" do appear in the title if it's not a Study.

**Comment by tosfos** [comment]
I agree that it's not necessary. I'd estimate around 3 hours to get it done.

**Comment by tosfos** [comment]
How should we proceed with this? @lwaldron

**Comment by lwaldron** [comment]
Let's leave it for now as a lower priority item.

**Comment by lwaldron** [comment]
I think this can be closed for now, the text search is working well.
