### ISSUE TITLE
NCBI taxid entry not working?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#79]
When I look at the taxon page for the [Enterococcaceae family (81852)](https://bugsigdb.org/Special:RunQuery/Taxon?Taxon%5BNCBI%5D=81852&_run=1) I see an orange integer taxon 526525 under signature [226:001:001](https://bugsigdb.org/Study_226/Experiment_1/Signature_1). Following that the link I don't see any integer taxon displayed, or the *Erysipelotrichales* order it refers to (NCBI [link](https://www.ncbi.nlm.nih.gov/taxonomy/?term=526525)). When I edit https://bugsigdb.org/Study_226/Experiment_1/Signature_1, I can see the integer 526525 entered, as instructed on the signature entry page. ("NCBI: Enter the name of a taxon. If autocomplete does not find it, enter a numeric NCBI taxon identifier by searching here"). 

When an integer NCBI taxid is entered by a curator, it should be treated the same as if the name were entered.

**Comment by tosfos** [comment]
From what I can tell, it's an issue with the underlying lookup from NCBI for this specific Tax ID. Why the lookup fails for this one ID is still a mystery, which we'll explore.

Are you seeing it for any other tax IDs? I did a quick check and didn't see any others.

**Comment by lwaldron** [comment]
I haven't heard of or seen any others...

**Comment by tosfos** [comment]
It looks like we had a bad value for this Tax ID stored in the cache. We have theories about why this happened, but it's not worth pursuing right now. If it happens again, we can reopen.

We cleared the cache and this issue is now resolved. Please review and close.

**Comment by lwaldron** [comment]
Looks good now.
