### ISSUE TITLE
https://bugsigdb.org/Property:Statistical_test cleanup

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#81]
The statistical tests (https://bugsigdb.org/Property:Statistical_test) use inconsistent capitalization, e.g.:
* **z**ero-inflated beta regression
* **Z**ero-inflated negative binomial regression

and some terms have no capitalization at all. Standardize on Title Case for all, such as currently used for "Linear Regression". This will require fixing the allowed values, then fixing pages containing the old values. (@tosfos could you advise on the best way to do this; there may be other properties that also require some clean-up? Is there a site-wide search and replace available?)

@rimsha1 would you document hot to do this kind of cleanup under the Information for Reviewers (https://bugsigdb.org/Help:Contents)?

**Comment by tosfos** [comment]
There is a site-wide search/replace [here](https://bugsigdb.org/Special:ReplaceText). Please let me know if you need additional assistance.

**Comment by lwaldron** [comment]
Looks great @rimsha1 thank you!
