### ISSUE TITLE
Remove section headings for empty sections

### ISSUE THREAD

**Issue by tosfos** [waldronlab/BugSigDB#82]
- Maybe remove headers with all missing values from the display (e.g. "Alpha Diversity" for Study_74.

_Originally posted by @chuttenh in https://github.com/waldronlab/BugSigDB/discussions/78#discussioncomment-859849_

**Comment by tosfos** [comment]
This is done. Please review @lwaldron .

Note how the empty Alpha Diversity section [is now omitted](https://bugsigdb.org/Study_74):
![image](https://user-images.githubusercontent.com/10228795/125504348-60c603c1-4fb0-4735-b81b-06647e1ce6db.png)

**Comment by lwaldron** [comment]
Looks good!
