### ISSUE TITLE
Maximum number of loops have been performed

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#83]
Seeing this right now on https://bugsigdb.org/Study_453# - not sure common of an issue it is:

![image](https://user-images.githubusercontent.com/639942/123977310-2ce33200-d9bf-11eb-978f-a0b2ac92d18d.png)

**Comment by tosfos** [comment]
This is now fixed. In theory it can still show up on another page with many more signatures, but that is unlikely. At some point, we'll hopefully re-work the code as it has grown to be quite complex.

**Comment by lwaldron** [comment]
Thanks @tosfos !
