### ISSUE TITLE
Add logos to the footer

### ISSUE THREAD

**Issue by tosfos** [waldronlab/BugSigDB#84]
Add the WikiWorks logo next to the MediaWiki logo, then to the left of that, add the CUNY log. Requested by @lwaldron.

**Comment by tosfos** [comment]
We added the logos to the footer. Here is a screenshot:

![image](https://user-images.githubusercontent.com/10228795/124628965-f7bb6180-de4e-11eb-89ed-63b1ff8ee9c5.png)

We'd like to do some graphic work to modify the 2 logos to look more like the adjacent logos, as right now it looks very inconsistent. Please let me know if we should go ahead with that. Please also let me know if we should change the logo order.

**Comment by lwaldron** [comment]
Yep please go ahead. For CUNY I should probably use a CUNY SPH logo, and there are a bunch of variants to work with at https://www.dropbox.com/s/cq9vbq9ojigo7qi/CUNY-SPH_brand-guidelines_v05.pdf?dl=0 (no need to worry about making some modifications to make it work, no lawyers will come after us!) You could link it to https://sph.cuny.edu/about/people/faculty/levi-waldron/. I would be inclined to put CUNY either at the right or the left of the other logos.

**Comment by tosfos** [comment]
We created the following logo images:

<img src="https://user-images.githubusercontent.com/10228795/124833480-400c7980-df4c-11eb-9b81-264f29b38167.png" height="31px">

<img src="https://user-images.githubusercontent.com/10228795/124833565-603c3880-df4c-11eb-9626-69e2510a3aba.png" height="31px">

As you can see, at this size there is too much detail in these logos to look right. We can remove certain elements such as the outline from the CUNYSPH logo if it's compatible with branding. Or we propose the following completely custom logo block:
![image](https://user-images.githubusercontent.com/10228795/124833677-8b268c80-df4c-11eb-99dc-dfa83119696a.png)
If we use this approach, we can also rework the WikiWorks logo to be more square if you'd like.

Please let me know how to proceed.

**Comment by lwaldron** [comment]
Your proposal looks nice to me. Perhaps we could clean up the footer text to make room to give prominent credit to funding and CUNY, something like this?

* Privacy policy -> not needed?
* About A Comprehensive Database of Microbial Signatures -> About BugSigDB (keep current link to Project:About)
* Disclaimers -> not needed?
* Funded by NIH 5R01CA230551 to the City University of New York (link to a new page Project:Team?)

**Comment by tosfos** [comment]
>  Privacy policy -> not needed?

Well it's definitely not needed if it points to a blank page! But the page might be required by law or be a good idea to fill it in. I am not a lawyer, though. Please let me know.

> About A Comprehensive Database of Microbial Signatures -> About BugSigDB (keep current link to Project:About)

This label is generated based on the site name, which is currently set to "A Comprehensive Database of Microbial Signatures". And that's probably incorrect. We'll change it to "BugSigDB". But the site name is used in many other places in the site, so let me know if you notice a place where "BugSigDB" has appeared in a context that it doesn't make sense. That probably won't happen though.

> Disclaimers -> not needed?

Removed.

> Funded by NIH 5R01CA230551 to the City University of New York (link to a new page Project:Team?)

Will do.

**Comment by lwaldron** [comment]
I've filled in the Privacy policy - took the easy way of saying we follow the WikiMedia privacy policy and linking to https://bugsigdb.org/Project:Privacy_policy, then listing exceptions. 

One exception I listed was Google Analytics with anonymized IP, but perhaps there is an extension you could install to create usage statistics instead? I opened this as issue #91 .

**Comment by tosfos** [comment]
> We'll change it to "BugSigDB".

This is now done:
![image](https://user-images.githubusercontent.com/10228795/125502682-10309774-4012-4f78-8f50-579fcfd78dc6.png)

**Comment by tosfos** [comment]
Please review the new custom footer logos. They are live on the site:
![image](https://user-images.githubusercontent.com/10228795/126846058-3d5d9ada-7b49-4792-91e1-2e42fdf08e05.png)

Please let me know if the size should be adjusted.

**Comment by tosfos** [comment]
We added the custom "funding" text:
![image](https://user-images.githubusercontent.com/10228795/126908965-54859b2b-7341-4c40-b879-19bbaeeee8f8.png)

**Comment by lwaldron** [comment]
Logos and funding text look good. A couple small things for the logos:
1. make the CUNY SPH logo link to https://sph.cuny.edu/about/people/faculty/levi-waldron/
2. put the CUNY SPH logo on the left, perhaps with a bit of a gap to delineate academic partners and software engineering partners.

**Comment by tosfos** [comment]
1. [Done](https://bugsigdb.org/Main_Page).
2. Done:
![image](https://user-images.githubusercontent.com/10228795/127705863-8df201a3-b438-49e6-86ff-4858399aa9c2.png)
