### ISSUE TITLE
User-friendly alternative to comma-separated integers in bulk export

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#85]
Comma-separated integers tend to get converted to numeric values in Excel in a non-reversible way, and R's popular "readr" package got fooled by this with default settings where it tries to guess column data types. It might save some user headaches to use a different separator for within-cell repetition (semicolon, since | is already used for taxonomy?).

**Comment by seandavi** [comment]
You could consider encoding nested data (like lists of integers) as JSON
since json parsers are both fast and available in every language.

```
> col_test = '[1,2,3]' # as opposed to 1,2,3 or 1|2|3
> df = data.frame(a=1:3,b=col_test)
> df
  a       b
1 1 [1,2,3]
2 2 [1,2,3]
3 3 [1,2,3]
> df$c = lapply(df$b,fromJSON)
> df
  a       b       c
1 1 [1,2,3] 1, 2, 3
2 2 [1,2,3] 1, 2, 3
3 3 [1,2,3] 1, 2, 3
> sapply(df,class)
          a           b           c
  "integer" "character"      "list"
```

**Comment by lwaldron** [comment]
@sean I was mostly thinking of non-computational biologists and Excel here, since the nesting here in the csv file is simple and probably not much of a barrier to someone writing a program. 

Just as a note, R users will have https://github.com/waldronlab/bugsigdbr (on its way shortly to Bioconductor). Whatever happens here will be hidden from users of bugsigdbr. JSON would be a friendly feature addition for programmers in other languages but I would probably give it lower priority.

**Comment by tosfos** [comment]
We propose that we add a property to the Signature pages with a semi-colon delimited list of taxon IDs. Then we'll switch the export functionalities to use this new field instead. Does that sound like a good solution?

**Comment by lwaldron** [comment]
Sounds good to me.

**Comment by tosfos** [comment]
We added the semi-colon delimiters to both types of CSV export. [Here](https://bugsigdb.org/Special:Ask/-5B-5BCategory:Signatures-5D-5D/-3FOriginal-20page-20name%3DSignature-20page-20name/-3FRelated-20experiment%3DExperiment/-3FRelated-20study%3DStudy/-3FSource-20data%3DSource/-3FCurated-20date/-3FCurator/-3FRevision-20editor/-3FDescription/-3FAbundance-20in-20Group-201/-3FNCBI-20export%3DMetaPhlAn-20taxon-20names/-3FNCBI-20export-20ids-20sc%3DNCBI-20Taxonomy-20IDs/mainlabel%3D-2D/limit%3D5000/offset%3D0/format%3Dcsv/searchlabel%3DDownload-20all-20Signatures-20(CSV)/filename%3Dsignatures.csv) is one from Help:Export and [here](https://bugsigdb.org/w/index.php?title=Special:Ask&x=-5B-5BCategory%3ASignatures-5D-5D-20-5B-5BModification-20date%3A%3A%2B-5D-5D-20-5B-5BBase-20page.Location-20of-20subjects%3A%3AUnited-20States-20of-20America-5D-5D%2F-3FOriginal-20page-20name%3DSignature-20page-20name%2F-3FRelated-20experiment%3DExperiment%2F-3FRelated-20study%3DStudy%2F-3FSource-20data%3DSource%2F-3FCurated-20date%2F-3FCurator%2F-3FRevision-20editor%2F-3FDescription%2F-3FAbundance-20in-20Group-201%2F-3FNCBI-20export%3DMetaPhlAn-20taxon-20names%2F-3FNCBI-20export-20ids-20sc%3DNCBI-20Taxonomy-20IDs&mainlabel=-&limit=5000&offset=0&format=csv&searchlabel=%3Cdiv%20class%3D%22mw-ui-button%20mw-ui-quiet%20mw-ui-progressive%20rounded-0%22%3ESignatures%3C%2Fdiv%3E&filename=signatures-filtered-united-states-of-america_20210731.csv) is one from the drilldown view.

**Comment by tosfos** [comment]
Can this be closed?

**Comment by lwaldron** [comment]
Yes, looks great.
