### ISSUE TITLE
A lot of WantedPages?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#87]
I found this from https://bugsigdb.org/Special:SpecialPages - these seem related to an older page naming convention? Not sure if these links need to be cleaned up but just wanted to point it out.

https://bugsigdb.org/Special:WantedPages

**Comment by lwaldron** [comment]
There are a lot of links on https://bugsigdb.org/Special:SpecialPages that I'm not sure what they do. Would defer to you @tosfos whether this page should be left as-is or pared down to eliminate irrelevant links.

**Comment by tosfos** [comment]
I wouldn't worry about items like
> Review:Study 105/Experiment 1/Signature 1‏‎ (3 links)

That's sort of the "Wanted pages" page working as intended. These are reviews that are missing. The naming convention is not quite "older". Even though we changed the page title display to **show** a Study name, the Study number is still used as the actual page title, as you can see from the URLs: https://bugsigdb.org/Study_81 . So these links are actually pointing to correct pages.

**Comment by tosfos** [comment]
> There are a lot of links on https://bugsigdb.org/Special:SpecialPages that I'm not sure what they do.

It's probably not worth going through these individually to determine if they are useful. Very few people will get here, and the ones that do will quickly figure out whether they belong there or don't. And almost all of these links are useful to somebody.

**Comment by tosfos** [comment]
We did notice that the "Wanted pages" list could use some cleanup. We'll check.

**Comment by lwaldron** [comment]
Sounds good - cleanup the "Wanted pages" but leave all the special pages intact.

**Comment by tosfos** [comment]
The Wanted pages are all cleaned up. This can be closed.
