### ISSUE TITLE
"Browse properties" appears twice in the "Tools" options

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#88]
See screenshot (taken from main page):

![image](https://user-images.githubusercontent.com/639942/125085421-d9fa3080-e0ca-11eb-97b5-7c86b2a3c1f6.png)

**Comment by tosfos** [comment]
Ah, yes. This is a Semantic MediaWiki bug that we identified on a separate project. The fix should be fairly simple.

**Comment by tosfos** [comment]
This was solved by updating SMW:

![image](https://user-images.githubusercontent.com/10228795/125502890-681f6873-3dca-4914-b7c6-e41842cbd7cf.png)

This can be closed.
