### ISSUE TITLE
site usage statistics

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#91]
I'd like to keep statistics on traffic to the site over time, and where in the world it comes from. It would also be useful to know about the popularity of pages, and which site features (ie search, drill-down) get used. This will be useful when it comes time to apply for funding for long-term site maintenance.  I'm not sure about pros and cons of Google Analytics vs an installed extension, so would appreciate suggestions. 

We already plot contributions at http://waldronlab.io/BugSigDBStats/articles/BugSigDBStats.html so it's not necessary to do more on this unless it's straightforward and can offer something extra. Here we plot things like:
* per-user and overall of contributions and revisions
* amount of information in the site.

**Comment by tosfos** [comment]
Browsers are beginning to block tracking JavaScript like the one used by Google Analytics. We often install Matomo to read from the server logs, which mitigates this issue and also avoids reliance on an external service. I would recommend Google Analytics either way as there's little downside to installing it, and often there are discrepancies in the way traffic is reported between the 2 tools.

Please let me know how to proceed.

**Comment by lwaldron** [comment]
Installing both tools sounds good to me. I set up a Google Analytics account and gave you access to it too; here's the gtag.gs code it gave me:
```js
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YKH03F3F5K"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YKH03F3F5K');
</script>
```

**Comment by tosfos** [comment]
Matomo is now available [here](https://bugsigdb.org/matomo/). I'll send the password privately.

**Comment by tosfos** [comment]
Note that Matomo only reads the logs once per day to update its data.

**Comment by lwaldron** [comment]
Matomo looks great! I was able to login and poke around a bit.

**Comment by lwaldron** [comment]
Google Analytics seems to be working too, so the issue looks closed to me.  Re-open if there's anything else to do.

**Comment by lwaldron** [comment]
It looks like the Matomo link no longer works (500 error) - https://bugsigdb.org/matomo/

**Comment by tosfos** [comment]
Sorry about that! It's back up now. We were able to recover logs from the last few weeks.

**Comment by lwaldron** [comment]
https://bugsigdb.org/matomo/ is returning an error:

Unable to write in the cache directory (/var/www/html/tmp/templates_c/62).

**Comment by tosfos** [comment]
Sorry. Checking.

**Comment by lwaldron** [comment]
On the topic of analytics, I just received a message from Google Analytics linking to  https://support.google.com/analytics/answer/12938611#zippy=%2Cin-this-article, saying that

> It's critical that you migrate your Universal Analytics property settings to [Google Analytics 4](https://support.google.com/analytics/answer/10089681), or you will begin to lose data on July 1, 2023 (July 1, 2024 for Analytics 360 properties). [Learn how](https://support.google.com/analytics/answer/10759417) to migrate your settings.

I'm not sure but I guess this means I need to create the new Google Analytics 4 property, then give you a new Javascript snippet?

**Comment by tosfos** [comment]
We're already using a new snippet, but we'll verify that nothing else needs to be done.

**Comment by lwaldron** [comment]
It looks like you already had administrative privileges to the bugsigdb.org "property":

![image](https://user-images.githubusercontent.com/639942/225270452-855c959e-da76-4baa-92d7-bcf618532dc3.png)

but not to the "waldronlab" account:

![image](https://user-images.githubusercontent.com/639942/225271269-ef71de7f-93d6-4b0e-888a-b162c3a50ad2.png)

![image](https://user-images.githubusercontent.com/639942/225271566-89a7a815-a3b1-40bb-9779-2bc9d336f075.png)

I just changed your waldronlab account access to "editor" although I would expect the effect of that would just be to give you access to other properties.

**Comment by tosfos** [comment]
Thanks. Not sure why I couldn't see the property before then.

It looks like the warning you received is regarding the other properties. The bugsigdb.org property is using Analytics 4 as it shows in the screenshot.

**Comment by tosfos** [comment]
> https://bugsigdb.org/matomo/ is returning an error:
> 
> Unable to write in the cache directory (/var/www/html/tmp/templates_c/62).

This is fixed. We're going to research what could have caused this.

This can be closed.
