### ISSUE TITLE
Body site ontology warning message

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDB#95]
There's a message that's appearing since yesterday by the body site field only in cases where the body site is "feces". Other body sites seem to be fine. Here's an example of a paper: https://bugsigdb.org/Study_453/Experiment_4
![image](https://user-images.githubusercontent.com/45443641/129071240-eef025ff-3d85-49ff-90cc-595a343add5c.png)

**Comment by ftzohra22** [comment]
Found another body site with this message: https://bugsigdb.org/Study_121

**Comment by tosfos** [comment]
Will check.

**Comment by tosfos** [comment]
Fixed. Please review and close.

**Comment by ftzohra22** [comment]
Thanks!
