### ISSUE TITLE
Unable to edit experiments

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#97]
@lgeistlinger and I are currently unable to edit any Experiment (e.g. https://bugsigdb.org/Special:FormEdit/Experiment/Study_317/Experiment_2?reload=1&returnto=Study_317). The message is:

> This page isn’t working
> bugsigdb.org is currently unable to handle this request.
> HTTP ERROR 500

Is this related to the addition of some tens of thousands of ontology terms to the allowed values? See #55

**Comment by tosfos** [comment]
We increased the timeout, so now the form will load. I'll follow up regarding the underlying performance issue.

**Comment by lwaldron** [comment]
@ftzohra22 is reporting still being unable to edit experiments. Should we just revert the addition of all the ontology terms to condition and body site until we have a better way to use these ontologies?

![image (1)](https://user-images.githubusercontent.com/639942/130761459-325163ad-b4e3-4fb1-8b61-5055434adeca.png)

**Comment by lgeistlinger** [comment]
Can confirm Fatima's observation. Reverting would be easy, however I think the current developments are important for getting the ontology handling on bugsigdbr.org in shape. Is there a way to continue the work that's under way on this ("devel branch") without disrupting ongoing curation work ("release branch")?

**Comment by lwaldron** [comment]
I just tried now and was able to edit the Study_440 Experiment_1, but Experiment_2 just remained a blank page. This should be the top priority to allow curators to get back to entering new data, even if it just means going back tot he fewer body sites and conditions that we had.

**Comment by lwaldron** [comment]
I just rolled back @lgeistlinger 's addition of the full ontologies - still just getting familiar with working with a MediaWiki and how easy it is to undo or redo changes. I just rolled back the edits on August 20 under "Recent Changes". I see that by clicking on the "hist" of Property:Body site/Values or Property:Condition/Values, it would be easy to re-apply those changes when we are ready to. I am still having issues with slow/infinite waiting times e.g. for Study_440, Study_442, but I see "Change propagation updates are pending" at https://bugsigdb.org/Property:Body_site/Values so this needs to be tested again in a while.

![image](https://user-images.githubusercontent.com/639942/131579004-cd2f3d12-b7cd-4e1c-a667-ff078577adaa.png)

**Comment by tosfos** [comment]
[This seems OK now](https://bugsigdb.org/Special:FormEdit/Experiment/Study_440/Experiment_2). Are you still seeing any issues?

I think the underlying performance problems will be fixed once we fully resolve https://github.com/waldronlab/BugSigDB/issues/89.

**Comment by lwaldron** [comment]
Yes, it was resolved by reverting the addition of all ontology terms.
