### ISSUE TITLE
Body site not in drilldown

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#98]
Is there a reason not to have Body site along with "Location of subjects" and "Host species" in the Drilldown?

https://bugsigdb.org/Special:RunQuery/Drilldown?_run=1

![image](https://user-images.githubusercontent.com/639942/131577626-02be4b77-7e06-4fbd-b85a-371486289f93.png)

**Comment by tosfos** [comment]
We had removed the Body site & Condition fields after the number of values was expanded. We added them back now that those lists have been shortened.
