### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by tosfos** [waldronlab/BugSigDB#99]

**Comment by tosfos** [comment]
We added Varnish for anonymous (not logged in) users. Even for complex study pages, they will now load near-instantly if that page is in cache (meaning that it was visited recently by an anonymous user). This will need adjustment over time, since it means that there may be some lag after a wiki page is changed before an anonymous user sees that change. Feel free to try this out! Log out of the wiki and visit a long [study](https://bugsigdb.org/Category:Studies) page. It may take a while to load. Then visit it again (even in a different browser) and it should load really fast. Right now, you can check with these pages.

**Comment by lwaldron** [comment]
Wow, it is FAST! Also the dynamic main page. That's fantastic. I don't see a problem with some lag after a wiki page is changed.

**Comment by lwaldron** [comment]
Just wondering if something is wrong with Varnish? It's taking me 6-8 seconds to load the dynamic main page in an  Chrome desktop incognito browser, and this seems to be confirmed by Google Pagespeed analysis: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbugsigdb.org%2FProject%3ADynamic_Main_Page&tab=desktop

**Comment by tosfos** [comment]
We're working on that page now and running into some trouble.

**Comment by lwaldron** [comment]
"featured taxon" sounds fine to me. How about just changing those daily or something?

**Comment by lgeistlinger** [comment]
This looks like it can be closed. Feel free to reopen.
